zoe/covid-tracker-react-native

src/components/CovidRating.tsx, src/features/ThankYouScreen.tsx, src/features/ViralThankYouScreen.tsx
Also, extract the logic of checking if a user should be asked to rate into it's own function.
=> Fix 'ask for rating' always being set to true on ViralThankYou

src/features/DrawerMenu.tsx, src/features/ScreenParamList.tsx, src/features/multi-profile/ConsentForOtherScreen.tsx, src/features/multi-profile/SelectProfileScreen.tsx, src/features/register/TermsScreen.tsx, src/features/register/gb/PrivacyPolicyUKScreen.tsx, src/features/register/gb/WelcomeRepeatScreen.tsx, src/features/register/gb/WelcomeScreen.tsx, src/features/register/us/BeforeWeStartUS.tsx, src/features/register/us/NursesConsentUS.tsx, src/features/register/us/PrivacyPolicyUSScreen.tsx, src/features/register/us/TermsOfUseScreen.tsx, src/features/register/us/WelcomeRepeatUSScreen.tsx
Pass in viewOnly route props to all Privacy & Terms screens to hide the buttons.
=> Optionally hide buttons on consent screens

src/features/register/OptionalInfoScreen.tsx
We're hampered with Android testing with the expo client because of an error in the client when trying to retrieve push tokens. This leaves our QA testing stuck in that they cannot proceed past the OptionalInfo screen when creating an account.
I've found a `Constants.appOwnership` value in Expo we can use to just skip that bit of code while in the Expo client, but run it normally in the full app. This enables our QA testers and us to test on Android without waiting for an app build.
We can revert it when the expo client is working properly again. It's supposedly down to some configuration change in Firebase...
=> Skip retrieving push tokens when in expo client 

src/features/register/us/TermsOfUseScreen.tsx
Fixes a bug where Users on the ResearchConsent would open the Terms Of Use but then go back into the general consent ('Terms') page, rather than their appropriate page, without noticing.
=> change replace to goBack on US Terms screen

src/CovidApp.tsx, src/features/ScreenParamList.tsx, src/features/login/LoginScreen.tsx, src/features/multi-profile/ConsentForOtherScreen.tsx, src/features/register/ConsentScreen.tsx, src/features/register/CountryIpModal.tsx, src/features/register/gb/WelcomeScreen.tsx, src/features/register/us/BeforeWeStartUS.tsx, src/features/register/us/NursesConsentUS.tsx, src/features/register/us/TermsOfUseScreen.tsx, src/features/register/us/TermsOfUseUSScreen.tsx
[1] This changes the name of the consent screen (currently used by US and UK) from confusing `TermsScreen` to `ConsentScreen` and also updates it's label in Screen Stack to be `Consent` instead of `Terms`
[2] This changes the name of the TermsOfUse screen (currently used by US only) from possibly confusing and generic `TermsOfUseScreen` to `TermsOfUseUSScreen` and also updates it's label in Screen Stack to be `TermsOfUseUS` instead of `TermsOfUse`
=> Rename legal screens

src/features/patient/YourHealthScreen.tsx
initial value of `smokerStatus` is `no`, an option that doesn't exist in the dropdown, so no default value is displayed to the user. The backend, however is sent the value of `never` in this case. This PR fixes the discrepancy between what the user sees on the screen (blank), and what is sent to the server (`never`).
=> Default smoker status to never -- the default option that exists.

src/features/multi-profile/ConsentForOtherScreen.tsx, src/features/multi-profile/ReportForOtherScreen.tsx, src/features/multi-profile/SelectProfileScreen.tsx
Attempts to fix the issues of users navigating backwards through profile creation pages, and solving the issue of revisiting patient screens to see them already populated by previous flows through the pages. This latter is a navigation issue in that if a page already exists on the navigation stack, then navigating to that screen redisplays that screen, rather than showing a new one. So the approach originally taken is correct, but it's important to preserve the stack before the Select profile page, which this PR attempts to do.
I've hit the limit of my TypeScript + generics knowledge, and patience, so I'll need help to refactor the `pushToCleanNavStack` and `cleanNavigationStack` methods into plain utility functions. So I've duplicated the code in SelectProfileScreen and …
=> Truncate navigation stack of future screens in profile creation/selection

src/CovidApp.tsx, src/features/ScreenParamList.tsx, src/features/assessment/StartAssessment.tsx, src/features/patient/StartPatient.tsx, src/features/register/OptionalInfoScreen.tsx
Create a StartPatient pseudo-screen to host the logic of which Patient screen to show first, and space to clean up the navigation stack possibly.
Left a todo note on OptionalInfoScreen since there's US-specific logic as to what the first screen is here that isn't replicated elsewhere, so uncertain whether this logic should be consistent across all routes into the Patient screens.
=> add StartPatient to direct all Patient flows to.

src/features/multi-profile/ReportForOtherScreen.tsx, src/utils/avatar.ts
Fix the navigate link to creating first profile to set the avatar image to "profile2". The create profile screen expects this value to be set by the previous page.
Then, when a patient arrives with an invalid avatar image, the header just displays the name of the currently selected patient, and not the avatar image. In those cases, I default to returning "profile10" as the avatar image.
=> Fix first added profile avatar image

src/features/DrawerMenu.tsx
In the drawer menu when there's a release-channel available (in published and app-builds), display `DEV` if the app is pointing to the `dev` release channel.
This is to allow QA testers to know they are using the correct testflight version of the app which points correctly to the dev release channel for testing.
UPDATE: Decided to only display (DEV) if the release channel is dev. That way it's not leaking any release-channel info (security through obscurity). That alleviates my discomfort security-wise.
=> Show in dev channel

src/features/multi-profile/SelectProfileScreen.tsx
When creating a new Profile and starting an assessment, navigating back to the Select Profile screen, it doesn't update to show this newly created profile.
Navigation fires events, one is a focus event when a screen receives focus. I listen for that event, and trigger a listProfiles call when it fires.
However, the focus event also fires when the screen is first entered. Which means componentDidMount also runs, populating the listProfiles. To avoid this duplicate call, I use a flag in the state, to ensure I don't  call the backend twice quickly.
But, removing the call from componentDidMount instead would have the effect in development of making a change, the screen refreshes, and the profiles disappear: because a reload won't trigger the 'focus' event, because it's not a navigation event. …
=> SelectProfile page: refresh profiles on returning via a back navigation

src/features/assessment/WhereAreYouScreen.tsx
This PR is to use new navigateAfterFinishingAssessment on WhereAreYouScreen for the "home" option - it was previously directing straight to the Thank You pages rather than showing the screen to suggest adding new profiles.
=> Fix nav on I'm at home option of WhereAreYouScreen. 

src/features/multi-profile/SelectProfileScreen.tsx
On first-entry to the Select Profile page, if the backend isn't zippy in its response, we end up doing two HTTP calls to the backend patient_list API endpoint. It's because I'm setting the `shouldRefresh` flag to true before the HTTP request promise has resolved.
So the fix is to await the first HTTP request to return before setting the flag, which enables the focus listener to do its work of updating the profiles when a user returns to the Select profile page.
=> Fix double GET on first-time Select Profile page.

assets/lang/en-US.json, assets/lang/en.json, src/features/patient/AboutYouScreen.tsx
Entering a postcode of > 8 characters results in a server 500 error, and no visible error on the page as to the issue.
The server returns a 500 error, and a null response. Because this is the response that's also returned when the server has an issue, it's impossible to tell the two states apart. But we know that the postcode is stored as an 8 character string, and it raises an exception when we attempt to put a longer string in it.
So in the meantime, this fix adds a max length validation rule to the postcode field to at least help the user towards entering a postcode the server can handle.
This is just a first step towards improving the User experience on this page. At least there's a fighting chance the user will correct the postcode field, knowing that that's the field with a …
=> validate max length of postcode.

src/features/SplashScreen.tsx
Noticed that the call to backend API getStartupInfo isn't wrapped in a try catch, so when it fails, users are left with a dark blue screen. Which a few 1-star reviewers have mentioned happening since Saturday.
I've wrapped it in a try catch block, and default to GB when it fails, so users at least get to the welcome screen.
I guess this is where we need to check for online status.
The only reason I stumbled on this was adding some API endpoints to the mock-server, and this endpoint was the first one I hit that was missing...
=> Wrap getStartupInfo in a try/catch

src/core/Config.ts, src/core/config/SE.json, src/core/config/US.json, src/core/config/default.json, src/features/Navigation.ts, src/features/assessment/StartAssessment.tsx, src/features/patient/AboutYouScreen.tsx
Both using a country-specific feature flag.
* Skip over the cohort screen (Population Studies, Your Clinical Study) in the StartPatient screenflow if the `enableCohorts` flag is false
* Add `showEthnicityQuestion` and `showRaceQuestion` feature flags, and disable both for Sweden.
I'm not happy with the async dependency on get country to get the  config file. It just means having to use component state to populate the values when they are retrieved. Otherwise we hit a race-condition, because render doesn't wait for componentDidMount'ed promise.
Also, props.navigation might be stateful, even though it just looks like a group of methods. So maybe passing it in on the SplashScreen is insufficient, and we need to pass it in on each component. running `Navigator.replaceScreen` had issues …
=> SWEDEN: Hide Cohorts and Race/Ethnicity

src/features/assessment/CovidTestScreen.tsx, src/features/assessment/HealthWorkerExposureScreen.tsx, src/features/assessment/LevelOfIsolationScreen.tsx
This PR:
- Keeps track of the newly created `assessmentId` on the first page of assessments (either `CovidTestScreen` or `HealthWorkerExposureScreen`)
This avoids creating new assessments whenever the user navigates back to the first page. Instead the existing one will be patched.
=> Avoid creating multiple assessments when user navigates back.

assets/lang/en.json, assets/lang/sv-SE.json, src/components/DaysAgo.tsx, src/features/multi-profile/SelectProfileScreen.tsx
This prepends "Last report: " to the date that is displayed on the cards on the select profile screen. This is due to user's reporting confusion as to what this date meant. 
Not planned
=> prepend "Last report" to date on select profile card

assets/lang/sv-SE.json, src/features/assessment/DescribeSymptomsScreen.tsx
Fixes translation and bad i18n keys reported by Camilla. 
This appears to fix issues reported with dropdown options and conditional logic. 
In a sperate PR: 
- Change all links to goto the Swedish pages
- Defaulting to metric (might just be a device / AsyncStorage thing - I need to test later). 
- Unable to see dropdown options >1 line.
=> Sweden Translation fixes

src/features/patient/YourWorkScreen/helpers.ts, src/features/patient/YourWorkScreen/index.tsx
Fixes dropdown option translations. These options are were previously defined in `YourWorkScree/helpers.ts` and imported before i18n.locale is initialised  and so the default `en` is used. Super odd though, as I would assume this would be called lazily and my ReactJS is not strong enough to figure out a better solution. 
```
Logging:
In helpers.ts
Locale: en
Running application on Pixel 2 XL.
Call to getConfig() in GetPatient
Locale: sv-SE
```
This only happens when you first launch the app. If you do an Expo live-reload, it no longer presents itself. Again ... not sure why? 
What do you think @jamesbrooks94 ?
=> Fix dropdown translation bugs

src/features/register/WelcomeRepeatScreen.tsx
3rd attempt to fix Welcome Repeat screen. Currently on smaller screen devices the Report button -- the primary call-to-action -- is off the screen, and the screen is unscrollable. This fixes it so the button is permanently fixed to the bottom of the screen -- so always visible -- and the over long welcome screen scrolls underneath it.
N/A
=> refix Welcome Repeat Screen

assets/lang/en.json, assets/lang/sv-SE.json, src/core/user/UserService.ts
Allow default profile name to be localised if not set (It's force-set to "Me" in the app and on the server, I think). This PR hacks around that to set it to a localised/translated "Me".
=> Localise default profile name when not set.

assets/lang/sv-SE.json, src/features/DrawerMenu.tsx, src/features/register/ConsentScreen.tsx
Sweden changes: update with Swedish links in the Drawer Menu. Small text updates for privacy and consent pages. And pointing Drawer Menu privacy policy to PrivacyPolicySV screen.
=> Fix se links

src/features/patient/AboutYouScreen.tsx
Stops form from continuously re-rendering switching between kg and lbs
=> Fix for default units

src/features/register/WelcomeRepeatScreen.tsx
Fix research link on WelcomeRepeat screen for Sweden to point to Swedish site.
=> Fix research link on the Repeat welcome screen.

assets/lang/sv-SE.json, src/components/ContributionCounter.tsx, src/core/Config.ts, src/core/config/SE.json, src/core/config/default.json
- Fix number separator for Sweden
- Fixes translation for immunosurpressants.
=> Fix number separator for Sweden

app.json
Had to do a second build of the app yesterday, so iOS build picked the correct push notification key from expo. This is the app.json used for the second build.
=> Notch build versions for 2nd build of 0.12

assets/lang/en.json, assets/lang/sv-SE.json, src/core/user/dto/UserAPIContracts.ts, src/features/assessment/DescribeSymptomsScreen.tsx
Adds the following Yes / No Dropdown fields to the DescribeYourSymptoms screen
-  red_welts_on_face_or_lips /  hasRedWeltsOnFace
- blisters_on_feet / hasBlistersOnFeet
- dizzy_light_headed / hasDizzyness
- nausea / hasNausea
- eye_soreness / hasEyeSoreness
- chills_or_shivers / hasChills
=> Add new symptoms

assets/lang/en.json, assets/lang/sv-SE.json, src/CovidApp.tsx, src/core/patient/PatientState.ts, src/core/user/UserService.ts, src/features/ScreenParamList.tsx, src/features/assessment/CovidTestScreen.tsx, src/features/assessment/ProfileBackDateScreen.tsx, src/features/assessment/StartAssessment.tsx, src/features/multi-profile/SelectProfileScreen.tsx, src/features/patient/AboutYouScreen.tsx, src/features/patient/YourHealthScreen.tsx, src/features/patient/fields/BloodPressureMedicationQuestion.tsx, src/features/patient/fields/RaceEthnicityQuestion.tsx
Adds a screen before assessment that will ask the user any profile questions that may have been added to the app after they have already signed up.
Ive moved the blood pressure medication here and added the race/ethnicity question. This involves moving those questions out into their own components and using them in their original screens as well as the new one.
It seems formik validation for the race question may have gotten broken before this, but it looks like its not working atm. I couldn't see the issue but will look again.
=> Add screen to ask back dated profile questions

src/core/patient/PatientState.ts, src/core/user/UserService.ts, src/core/user/dto/UserAPIContracts.ts, src/features/assessment/CovidTestScreen.tsx, src/features/patient/AboutYouScreen.tsx
This implements a tactical work around that preserves that presents just the key question (i.e the date of the test) that product & researchers need first. The rest of https://github.com/zoe/covid-app/pull/152/files will be adapted into a different flow as requirements have shifted. 
```
{
"patient": "be428fa3-043a-41ac-9ca9-f8cb44da1493",
"had_covid_test": false,
"version": "1.3.2"
}
```
```
{
"patient": "be428fa3-043a-41ac-9ca9-f8cb44da1493",
"had_covid_test": true,
"tested_covid_positive": "waiting",
"version": "1.3.2"
}
```
```json
{
"patient": "be428fa3-043a-41ac-9ca9-f8cb44da1493",
"had_covid_test": true,
"tested_covid_positive": "no",
"date_test_occurred_guess": "less_than_7_days_ago",
"version": "1.3.2"
}
```
### Test 4
```
{
"patient": "be428fa3-043a-41ac-9ca9-f8cb44da1493", …
```
=> Strip Down Covid Test Screen

src/features/assessment/StartAssessment.tsx, src/features/patient/AboutYouScreen.tsx
Navigation to back date screen was still happening on SE locale for disabled questions.
=> Stop navigation to back date profile for disabled question on se locale

app.json, assets/lang/en.json, assets/lang/sv-SE.json, src/features/SplashScreen.tsx
Add an error dialog when we fail to fetch startup info. This should also fix #31 (although it seems we don't show a blank screen anymore). Let me know if you want me to change the wording of the message!
Question: Calling `bootstrapAsync` again shows an error message on the simulator (it seems to be related to changes to the navigator this function makes), but this won't be shown on a prod build. Nevertheless, I was thinking whether we should wait before making changes to navigator, etc?
This is my first time with React Native so apologies in advance for any mistakes!
=> [Splash] Show an error dialog when startup info fails to fetch

src/components/DropdownField.tsx, src/features/assessment/CovidTestScreen.tsx
Dropdown/pickers are inconsistent between iOS and Android. If the selectedValue of the dropdown doesn't match any entries in the dropdown, iOS leaves the displayed item blank / shows a placeholder, but Android defaults to showing the first available item in the dropdown.
This raises an issue that bites us multiple times -- to the user there's a selected item showing, but to the app the selected value isn't that of the item showing. That mismatch leads to confusion where the user is told he needs to pick a value, but he can clearly see one already picked, and leading him to believe the defaulted item isn't selectable, and he must chose another. Or feel like he is stuck on the page and cannot continue.
We had this issue on adding the any blood medication question on the Covid screen. And …
=> Android Dropdown - create placeholder when selected value not listed

assets/lang/en.json, assets/lang/sv-SE.json, src/components/BrandedButton/__tests__/BrandedButton.test.native.tsx, src/components/Text.tsx, src/features/assessment/CovidTestScreen.tsx, src/features/assessment/LevelOfIsolationScreen.tsx, src/features/assessment/StartAssessment.tsx
Change isolation question to capture both level of isolation, and frequency of interactions
Also prevent errors from showing up until user hits submit. 
Translations also included
Unable to test on Android device an emulator so please double check.
Use this fix for errors displaying before submit on other pages.
=> replace existing isolation questions

src/core/user/dto/UserAPIContracts.ts, src/features/assessment/LevelOfIsolationScreen.tsx
Previously if you submitted once with incorrect, you would then be unable to re-submit, even with correct answers and the BrandedButton's enable prop would be set to `false` but `validationOnChange` and `validationOnBlur` were also set to `false` so would never re-check the input validation.
This PR re-sets `validationOnChange` and `validationOnBlur` to `true`, but only allows validation errors to appear once the CTA Button has been clicked at least once, via Formik's built-in submitCount prop. 
I did not need to as mockServer doesn't contain assessment fields.
If we're happy with this approach, apply it to existing pages with validation.
=> Fix Validation on LevelOfIsolationScreen

src/features/assessment/ProfileBackDateScreen.tsx
On Backfill screen for US where race/ethnicity has already been populated, the Backfill profile screen blocks on an ethnicity validation. So added a conditional check that the needsRaceAnswer is set along with the rest of the validation.
=> Condition race and ethnicity validation on needRaceAnswer.

assets/lang/en.json, assets/lang/sv-SE.json, src/features/assessment/LevelOfIsolationScreen.tsx
At the moment the error message is unclear if you enter a non-integer answer, vs a negative answer (for whatever reason). Screen shots show with and without main error cases.
=> Better error message on isolation screen

src/features/assessment/CovidTestDetailScreen.tsx, src/features/assessment/DescribeSymptomsScreen.tsx, src/features/patient/YourWorkScreen/index.tsx
I've previously fixed the dropdowns so that in Android it automatically gets populated with a "please select" option if the selected value doesn't match an available option item value.
This makes `androidOption` method redundant, so I've removed it from all fields.
=> remove androidOption from dropdowns

src/features/assessment/DescribeSymptomsScreen.tsx
Fix temperature defaulting on Report Symptoms Screen
=> Fix temperature defaulting on Report Symptoms Screen

src/features/assessment/ProfileBackDateScreen.tsx
Correct error strings on the backdating screen for the PeriodAge
=> Correct i18n

appConfig.ts, assets/lang/en.json, assets/lang/sv-SE.json, src/components/Badge.tsx, src/components/Donate.tsx, src/components/ShareThisApp.tsx, src/components/VisitWebsite.tsx, src/features/ThankYouScreen.tsx
This PR add's a new Donate Module, for the UK App, on to the ThankYouScreen. This screen is currently shared between Sweden and UK. 
This PR also begins to refactor the ThankYou Screen into smaller components:
- ShareThisApp
- Donate
- CoralBadge
- VisitWebsite 
The ShareThisApp component has two variants: One where the CTA is a button and one where it is a link. The CTA on ShareThisApp is set to "link: when the Donate module is present (i.e. The UK App) so there aren't two CTA buttons on the same screen. 
Swedish translations are deliberately left out for the Donate Module. 
A separate ticket will unify the different thank you experiences.
=> Add donate module to Thank You Page

.circleci/config.yml
Fix CircleCI to actually wait for approval before running the OTA expo publish
=> Actually wait for approval before running the OTA expo publish

src/features/Navigation.ts
Fix condition Navigation to use the correct countryConfig flag. 
This has no impact> Sweden currently has enablePersonalInformation = False and enableMultiplePatient = False. US and UK have both values set to True. 
However this may not alway be the case.....
=> Fix condition Navigation to use the correct countryConfig flag. 

src/features/Navigation.ts, src/features/register/ConsentScreen.tsx
We want to remove the optional data screen for normal US consent users. This is somewhat of a work around as I am modify the county config on the go, but I think its the simplest way, happy for other suggestions.
=> Remove us optional data screen for normal consent

assets/lang/en.json, src/CovidApp.tsx, src/Services.tsx, src/components/ErrorMessageBar.tsx, src/components/FlexView.tsx, src/components/Loading.tsx, src/components/OfflineNotice.tsx, src/components/Splash.tsx, src/core/ApiServiceErrors.ts, src/core/offline/OfflineService.ts, src/core/user/UserService.ts, src/features/DrawerMenu.tsx, src/features/Navigation.ts, src/features/SplashScreen.tsx, src/features/multi-profile/ConsentForOtherScreen.tsx, src/features/multi-profile/SelectProfileScreen.tsx, src/features/register/OptionalInfoScreen.tsx, src/features/register/WelcomeRepeatScreen.tsx
Network/Server errors come in two forms: ones that can be retried, and ones that can't or shouldn't. Errors because the User is offline, or the server is busy (429 errors) are those that can be retried. 404 errors can't be retried, the resource isn't there, retrying isn't going to change things.
When the user is presented with a retry button, we're wrapping the handler of that in a 5 second pause, but indicating that the app is retrying the request. That way, we are doing a basic throttling of requests, giving the server at least a little time to scale up to handle the current volume of requets. We can evolve that delay in future, e.g. increasing the delay after each failed request.
* SplashScreen - instead of a plain blue screen, there's now a Covid logo, and underneath that a status …
=> Improve error handling

src/components/DaysAgo.tsx, src/features/multi-profile/SelectProfileScreen.tsx
This PR adds a green tick to the top right of the avatar picture if the user has reported today. Tick has been added with absolute positioning in a view of fixed size so should be in the same position regardless of screen size. Small refactor to use same logic as `DaysAgo` component.
Tested on multiple screen sizes (see below).
iPhone 11 Pro Max
iPhone 8
Android (Blackview BV5800)
N/A
=> Add checkmark for profiles reported today

src/components/Checkbox.tsx, src/features/register/ConsentScreen.tsx, src/features/register/us/NursesConsentUS.tsx
Following the re-design in #279, this PR switches the remaining checkboxes to the new style.
These were located on the consent screens. 
As a result, this PR:
[1] Switches CheckboxItem from using `TouchableWithoutFeedback` to using `Item`, in order to allow children (in this case `ClickableText`) to still function correctly. 
[2] Switches the US and SE standard consent screens to use the new checkbox style.
[3] Switches the US study consent screen to use the new checkbox style.
=> Switch consent screens to use new style checkbox

src/core/LocalStorageService.ts
LocalStorageService is just a simple API wrapper around AsyncStorage, with a generic-based method interface. So it supports serialising/deserialising plain data objects, stashing them into AsyncStorage as JSON documents.
=> Simple storage wrapper around AsyncStorage.

src/core/api/ApiClient.ts, src/core/user/UserService.ts, src/core/utils/platform.ts
Starts an API client that wraps APIClient base, with generic HTTP methods so we can separate out the services from the backend API they persist data. This implements just enough to support PushNotificationService.
Every service that needs to communicate with the Backend API will talk to a service specific API client, which in turn talks to this API Client, which wraps Axios. Because this API client wraps the ApiClientBase it inherits the userToken management, so we can do authenticated requests without each service having to deal with it itself.
This is necessary step to break apart User Service in a meaningful way,
=> Create API client

src/components/Loading.tsx, src/features/multi-profile/SelectProfileScreen.tsx, src/features/register/OptionalInfoScreen.tsx
* Bob 2: Turn off isApiError flag before exiting the SelectProfile screen.
* Bob 3: replicated it once, but not again. Have traced a possible cause of `"Text strings must be rendered within a <Text> component"` and fixed that, and applied the same fix as Bob 2 prior to navigating off the page. Can't confirm Bob 3 is fixed yet.
Bob 2 fixed:
https://www.dropbox.com/l/scl/AAASpxDRtCPmauPXZE2U_s4_BIeVs1zGSmU
=> fixing bob issues

assets/lang/en.json, assets/lang/sv-SE.json
As a result of the new i18n tests, it's picked up 3 discrepancies between en and sv-SE.
* In `sv-SE` but not in `en`: `placeholder-has-diarrhoea` -- not in use, so REMOVED
* In `en` but not `sv-SE`: `picker-never-had-test` and `do-you-use-a-stick`, both not in use, so REMOVED.
=> Fix i18n strings mismatches between en and sv-SE.

assets/lang/en.json
As part of the work around the Validation Study, we have to adjust our brand positioning alongside KCL's.
This is a simple ticket ahead of the general ThankYou screen refactor, to change the top text from "Thank you for joining millions of people supporting scientists at King's College London to help our health services"
to
"Thank you for reporting. As we ease lockdown, your daily reporting is more important than ever to avoid a second wave."
=> Update uk thank you screen

src/features/patient/YourStudyScreen.tsx
Adds 2 US cohorts for Tuesday's launch. 
- [y] iOS - Emulator
=> Adds 2 US cohorts

markdown.d.ts, package-lock.json, package.json, src/components/InlineFormatting.tsx
Allows very basic inline formatting of strings, e.g. i18n strings.
=> Add inline formatting of text strings.

assets/lang/en.json, assets/lang/sv-SE.json, src/features/assessment/CovidTestDetailScreen.tsx
Don't show current date as the default value for the date picker. And fix the styling.
Default placeholder text:
Date selected text:
=> Fix default test picker date

src/features/ThankYouScreen.tsx
Removes the donation module from the UK ThankYourScreen, as we don't want this live as we launch the validation study. I've left the Donation component in the code base for now. 
=> Removes the donation module 

assets/lang/en-US.json, assets/lang/es.json, src/features/patient/YourStudyScreen.tsx
Screen now refers to an i18n tag which was renamed for GB users. 
This fixes that.
=> Fix i18n bug introduced with ES locale

src/core/Analytics.ts, src/features/register/gb/ValidationStudyConsentScreen.tsx, src/features/register/gb/ValidationStudyIntroScreen.tsx
Adds two track events on the Validation Study Consent Screen to track the who joins and who declines. 
Whilst we can infer this data from the Backend data or from the Screen View events, this will make it much much easier.
@abubuwe Proposal to cherry pick and OTA this tomorrow. 
=> Add Analytics to the Validation Study Consent

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/CovidApp.tsx
The various consent and privacy policy screens use React Navigator's Header titles, which are passed in as options on the screens in navigator. These 5 screens has missing Spanish translations for the titles. 
After an initial attempt to internationalise them, I gave up. 
On iOS the "Back" label  uses the previous screen name's title. 
Longer titles (especially in Spanish) and the "Back" button were causing display issues. 
This PR fixes the issues described above by:
- removing titles on the 5 consent & privacy policy screens. 
- overriding iOS behaviour to always use "Back" for the label of the back button. 
=> Remove screen titles and change iOS back button text

src/core/user/UserService.ts, src/features/register/constants.ts
Pass the App Consent version down to the backend, when determining whether to invite onto the study. People only the older version of the app, which have v1 of the study consent will not be invited to join. 
What's become very clear to me, is the the Consent Text needs to be in the backend. This can be done then next time we change the consent. 
=> Pass down consent_version 

src/components/GenericTextField.tsx, src/components/ValidatedTextInput.tsx, src/components/ValidationError.tsx, src/features/assessment/LevelOfIsolationScreen.tsx, src/features/patient/AboutYouScreen.tsx, src/features/patient/fields/PeriodStoppedAge.tsx, src/features/patient/fields/WeeksPregnant.tsx
Moves remaining simple text input questions to use the `GenericTextField` component. 
Moves the error message into the `GenericTextField` with an additional showError flag to maintain existing behaviour with error messages.
This PR maintains existing behaviours but is in preparation for design updates.
Potentially add the remaining error messages to other questions that use GenericTextField and deprecate the `showError` flag. 
Add info/description to justify new questions + UX & Styling changes to `GenericTextField`s as part of #230.
=> Migrate more questions to use GenericTextField

src/utils/datetime.test.ts, src/utils/datetime.ts
Fix the date calculation. the `startOf('day')` is necessary. But thankfully, moment converts all parsed date times into the current timezone correctly, even if one of the dates is in UTC.
=> Fix date calculation to get today and yesterday correct.

src/features/register/gb/ValidationStudyConsentScreen.tsx
Only allows accept consent to be pressed once.
=> Stop multiple presses of consent accept button

src/core/pushNotifications/PushNotificationService.ts
`apiClient.post` was updated to accept two type parameters, but PushNotificationService wasn't updated with this breaking change. So this is to fix that. We wouldn't have noticed this in test -- though I'm surprised TestFlight didn't pick it up and crash...
=> Add missing 2nd type parameter to Push Notification api call.

src/components/DrawerToggle.tsx, src/components/NewProfileCard.tsx, src/components/ProfileCard.tsx, src/features/multi-profile/SelectProfileScreen.tsx, src/features/register/WelcomeRepeatScreen.tsx
[Series of PR's for the Delete Profile feature]
Refactor the drawer toggle into separate component, which is used on the WelcomeRepeatScreen and the SelectProfileScreen. 
This also aligns the icon so they are in the same position across both screen - and the same position as the "close" icon on the drawer. 
=> Refactor the DrawerToggle and Profile Card

src/components/ProfileCard.tsx
Hide edit profile icon on main profile, as there is nothing interesting for the user to do on the main profile at the moment. 
=> Hide edit profile icon on main profile

src/features/multi-profile/ArchiveReasonScreen.tsx
Posted value didn't match corresponding backend value.
=> Fix backend value for duplicate account archive reason.

src/core/user/UserService.ts, src/features/register/constants.ts
This PR passes the Study Consent adVersion (v2) in this case. So we can track how many times we've asked the user different versions of the Study Advert. 
Related backend PR:
https://github.com/zoe/covid-app/pull/214
- [] iOS - Emulator
=> Pass adVersion down when accepting / declining Study Invite

mock-server/mockServer.ts, src/core/content/ContentService.ts
- Switch countryCode and langauge when calling function
- Adds a mock server.  
=> Fixes for fetching welcome screen text from backend. 

src/core/user/UserService.ts, src/features/register/WelcomeRepeatScreen.tsx
Currently the languageLocale sent on the query_params on the backend call for App Text is set from Localisation.locale - which could be any language code as it's based on the device setting, 
This PR changes it get set this query param from i18n.locale. This can only be one of `en`, `es` or `sv`. 
This also changes the behaviour the what is save on user creation on the user.language_code backend model. This is better! 
I've tested country accounts for US, SE and GB with device language as "English" and then again with "French" 
=> Fixes for locale when fetching AppText

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/components/DropdownField.tsx, src/components/ValidationError.tsx, src/features/assessment/CovidTestDetailScreen.tsx, src/features/assessment/DescribeSymptomsScreen.tsx, src/features/assessment/LevelOfIsolationScreen.tsx, src/features/assessment/ProfileBackDateScreen.tsx, src/features/patient/AboutYouScreen.tsx, src/features/patient/PreviousExposure.tsx, src/features/patient/YourHealthScreen.tsx, src/features/patient/YourStudyScreen.tsx, src/features/patient/YourWorkScreen/index.tsx
[1] Fixes validation error alignment so that dropdowns and generic text fields are aligned
[2] Remove the list of formik field names that need changing and replaces with a simple error. 
[1]
[2]
=> Fix validation error alignment

README.md
This feels tailored for Mac users, not sure if it'd work (or if the issue would even apply) to WIndows users. 
Any comments/changes welcome but this feels straightforward
=> Update README.md with fix for deprecated module import.

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/core/patient/PatientState.ts, src/core/user/UserService.ts, src/features/assessment/AssessmentCoordinator.ts, src/features/assessment/ProfileBackDateScreen.tsx, src/features/patient/YourHealthScreen.tsx, src/features/patient/fields/DiabetesOralMedsQuestion.tsx, src/features/patient/fields/DiabetesQuestions.tsx, src/features/patient/fields/DiabetesTreatmentsQuestion.tsx
[1] Adjusted justification copy to indicate questions are optional
[2] Switched to using a shouldAskExtendedDiabetes variable to conditionally render on the backfill page
[3] Switch BACK to using state to conditionally render questions on the YourHealth screen
[4] Add diabetes DTO to payload on YourHealth screen
[5] Updated DiabetesTreatment pfnts option as was too long for backends max_length
[6] Conditionally add numeric values to payload on Diabetes questions
[7] Add meaningful and translatable error message to Treatment question when no option selected
[8] Remove validation on oral meds question (users can simply not answer)
=> Bug fixes on new diabetes questions

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, mock-server/config.ts, mock-server/mockDb.ts, mock-server/mockServer.ts, mock-server/types.ts, src/CovidApp.tsx, src/core/assessment/AssessmentApiClient.ts, src/core/assessment/AssessmentService.ts, src/core/assessment/dto/LifestyleRequest.ts, src/core/assessment/dto/LifestyleResponse.ts, src/core/patient/PatientState.ts, src/core/user/UserService.ts, src/core/user/dto/UserAPIContracts.ts, src/features/ScreenParamList.tsx, src/features/assessment/AssessmentCoordinator.ts, src/features/assessment/LifestyleScreen.tsx, src/features/assessment/YourCovidTestsScreen.tsx, src/features/assessment/fields/LifestyleQuestion.tsx, src/features/patient/AboutYouScreen.tsx, src/features/patient/fields/WeightQuestion.tsx
- Adds a Lifestyle Screen that hosts 5 questions. 
- These questions are posted to a new API endpoint, but is logically within the assessment flow
- In the future, we might re-ask this question, which would post a new entry in the Lifestyle table in the backend
- A minor refactor alllows us to reuse the WeightQuesion from the AboutYou Screen here. 
- Updated mockserver
- Asking this question / displaying the screen in the assessment is driven by a flag returned by the Patient endpoin. 
=> Add's Lifestyles questions

appConfig.ts, assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/core/assessment/AssessmentService.ts, src/features/assessment/fields/LifestyleQuestion.tsx
Add Unsure as an option of Lifestyle Questions
Quick front end change to language only. Change "Prefer not to say" → "Unsure / Prefer Not to Say".
=> Update one of the lifestyle answer to include unsure.

src/features/assessment/CovidTestListScreen.tsx
Fix bad dropped line that prevents navigation from the CovidListScreen
=> Fix bad dropped line

src/features/DrawerMenu.tsx
Moves the position of the version. This is because, when also showing the revisionID, it was spilling out of the Menu and onto the WelcomeRepeat screen.
=> bug/Move version position on DrawerMenu

src/components/ContributionCounter.tsx, src/features/CountrySelectScreen.tsx, src/features/login/LoginScreen.tsx, src/features/register/Welcome2Screen/Welcome2Screen.tsx
LoadUser was being called and reseting the selected country. If logged in this doesn't matter, but on the initial screens it would cause the wrong country to be selected.
=> Inject user service so loadUser is not unnecessarily called

src/components/CalendarPicker.tsx, src/features/assessment/fields/CovidTestDateQuestion.tsx
Updates the styling for the calendar to prevent it from spilling out of the central view on some devices.
=> Update styling for COVID Test calendar

src/core/user/dto/UserAPIContracts.ts, src/features/assessment/fields/CovidTestMechanismQuesion.tsx
Where the Covid Test mechanism dropdown is set to "other" and then the user specifies free text, this free text is stored in the same field as the dropdown options (which should have been a typed enum). 
This then breaks, when you goto edit the Covid Test...
This PR fixes that by checking the mechanism value is one of the valid values for the dropdown. 
=> Fixes selection of mechanism other

src/features/SplashScreen.tsx
When refactoring the navigation + splash screen I introduced a bug by not awaiting an async call to fetch the logged in patient ID. This would then navigate the user to the welcome1 screen.
=> Fix bug not waiting to retrieve patient

src/features/AppCoordinator.ts
Fixes issue when expecting patient id when it may be null which causes a crash.
=> Fetch current patient only if patient id exists

src/core/user/UserService.ts, src/features/SplashScreen.tsx
Fix splash screen issue. 
Call to `await appCoordinator.init(this.props.navigation as NavigationType)` can throw an error and so you can get stuck on the SplashScreen. 
=> Fix splash screen issue.

src/Services.ts, src/core/diet-study/DietStudyApiClient.ts, src/core/diet-study/DietStudyCoordinator.ts, src/features/AppCoordinator.ts, src/features/DrawerMenu.tsx, src/features/ScreenParamList.tsx, src/features/diet-study/DietStudyAboutYouScreen.tsx, src/features/diet-study/DietStudyTypicalDietScreen.tsx, src/features/diet-study/DietStudyYourLifestyleScreen.tsx, src/features/diet-study/fields/EatingWindowQuestions.tsx
- Creates a basic dietStudyCoordinator.
- Wires up the DrawerMenu to the first 2 question screens and submit data to the survery. 
TODO:
- We need to figure out a way of knowing if you're on the first pass (possibly set `display_name = June`) or if we are on the second pass? 
- Fixes problem with 24 hours times expected on the server
=> Wire Diet Study Screens with a DietStudyCoordinator

.circleci/config.yml
Disables the build + publish to App Center. Unnecessarily bloats the release process, given that no one is using App Center in the team.
=> Disable Fastlane CI Step

src/core/diet-study/DietStudyCoordinator.ts, src/core/user/UserService.ts
Make API to fetch and set first patient profile when user selected Diet Study from Drawer menu
TODO: Show user there is no profiles?
=> bug: set default patient profile before starting diet study

src/core/AsyncStorageService.ts, src/core/diet-study/DietStudyCoordinator.ts, src/features/AppCoordinator.ts, src/features/DrawerMenu.tsx, src/features/diet-study/DietStudyIntroScreen.tsx
Store diet study skip option in local storage.
TODO: Decide on API call to store value in patient profile?
=> feat: show diet study intro if needed, after profile is selected

README.md
This is a minor fix on a instruction in which previous line in `.env` is replaced, not prepended to next one.
=> Fix a minor issue with a installation step

src/features/DrawerMenu.tsx
Only show drawer item for UK user
=> fix: show diet study nav for uk user only

src/features/register/Welcome1Screen.tsx
Adds Sign In button to 1st screen as well as second
=> add Sign In button to Welcome 1 screen

assets/lang/en.json, src/core/diet-study/DietStudyCoordinator.ts, src/features/diet-study/DietStudyFormSubmit.hooks.tsx, src/features/diet-study/DietStudyTypicalDietScreen.tsx
[1] Update placeholder text for clarity
[2] Reset navigation before starting second pass. This fixes a problem when finishing the first pass of the Diet Study, and when you start the second pass the form is pre-populated and scrolled to the bottom. The navigate action takes you "back"  to the previously populated screen as it's in the navigation stack history. 
[3] Fix missing patch at the end of the third screen, by calling `await form.submitDietStudy(infos)` before the block the changes the `timePeriod`
[4] Remove unused param `isComplete` on submitDietStudy function.
=> Diet Study Flow Fixes

src/features/diet-study/fields/SupplementQuestions.tsx
Fixes the CreateDTO for supplements question which was setting the supplements_other tag to be an array object. 
=> Fix submit supplements

src/core/AsyncStorageService.ts
Rename async storage key and variable name used for Diet Storage consent. 
=> Rename async storage key and variable

src/features/multi-profile/SelectProfileScreen.tsx
This makes sure that profiles are reloaded when coming back to this screen and green ticks are shown.
=> Make sure useEffect is not only called once on mount

src/features/thank-you/ThankYouUKScreen.tsx
On the UK page the secondary CTA "Report for Others" will do a back navigate to the Select Profile screen, as it's on the stack. Instead we replace the stack and it refreshes the patientList() from the backend (once!)
=> Fixes bug with out of date Profile List

assets/lang/en.json, src/core/diet-study/DietStudyCoordinator.ts, src/core/user/UserService.ts, src/features/menu/DrawerMenu.tsx
Allow users to return to the Diet Study from the Drawer Menu. The Icon is only shown for UK users who are in the rollout percentage. 
If they don't have any complete records, they'll start from the begining of the flow. 
If they've completed July 2020, then they'll start from the Welcome Break / Sarah Page
If they've completed both flows
In a follow up PR: 
- add a badge icon if they have incomplete studies. 
- Potentially add a CTA somewhere. 
=> Resume Diet Study from the Drawer Menu

src/components/DropdownField.tsx, src/features/diet-study/fields/EatingWindowQuestions.tsx
Caps the length of the dropdown to prevent it spilling out smaller screens and causing difficulty.
=> cap length of dropdown

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/components/GenericTextField.tsx, src/features/diet-study/fields/OtherInfoQuestion.tsx
Added a limit to other info text field on diet study
=> feat: limit input & added caption / validation on other text field

src/core/content/ContentService.ts, src/core/user/dto/UserAPIContracts.ts, src/features/AppCoordinator.ts
Use show_new_dashboard returned on startup_info to drive the behaviour of the HomeScreen. 
Thanks @snack-0verflow for laying the ground work for this!
=> Drive Welcome Repeat screen from server response

package.json, src/components/Cards/EstimatedCasesMapCard.tsx, src/features/EstimatedCasesScreen.tsx, src/utils/files.ts
WebView has issue loading file through `require('file.html')` on Android.
=> fix: load map differently. uses HTML string.

src/features/thank-you/ThankYouUKScreen.tsx
Added `Dashboard` to nav stack while resetting, also set current nav index to `SelectProfile`
=> fix: add 'Dashboard' to nav stack when resetting

src/components/Cards/EstimatedCasesMapCard.tsx
- Added arrow to map card on empty state
- Made Map clickable / touchable, will navigate to full screen map
=> fix: added arrow on empty state & made both maps clickable

src/features/AppCoordinator.ts
Enforce GB users for new dashboard
=> fix: enforce GB only for new dashbaord

src/components/USStudyInvite.tsx, src/core/Experiments.ts, src/core/consent/ConsentService.ts, src/core/patient/PatientService.ts
Fixes a problem when dismissing a the US Study Invite Modal. (Only shown for new US users). 
This was a caused by a circular reference between between ConsentService and PatientService. 
The USStudyInvite "consent" is an anomoly - as the flag is on the patient model. So `setUSStudyInviteResponse` really does belong in the PatientService.
=> Fix US Study Modal

src/core/AsyncStorageService.ts, src/core/user/UserService.ts
- Backend PR is up to clean up the Delete user endpoint, which too the username as payload JSON, whereas it's implicit - you can only delete yourself as the authenticated user. 
- This results in a clean more RESTFul delete endpoint and it also allows us to remove the saveProfile and getProfile from AsyncStorage.
=> Clean up Delete Data Endpoint & AsyncStorage

src/components/Cards/EstimatedCasesMapCard.tsx
- New container to use for snapshot container's ref (no more rounded corners in snapshot image)
- Share button no longer within the container for the shareable image
=> fix: move snapshot ref to another container

src/features/AppCoordinator.ts, src/features/login/LoginScreen.tsx
Triggers a refetch of startupInfo on Login to ensure any returning users, or users who've logged out for any reason still see the dashboard.
=> Fix/Refresh homescreen data on Login

src/components/Cards/EstimatedCasesMapCard.tsx
=> Fix button style

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/components/NewProfileCard.tsx, src/components/ProfileCard.tsx, theme/colors.ts
- Remove the 'i' icon for edit profile
- Add touchable text "Edit profile"
- Add non-touchable text "Create"
=> feat: update 'edit profile' / 'create'

src/components/Screen.tsx
Adds a bottom margin to screen element to always have gap between bottom and any elements. This makes sure buttons don't sit on the bottom line of the screen.
=> Add bottom margin to screen

README.md, package.json
I've updated the readme to include a total reset command. A common clear cache command.
Added link to setting up multiple simulators for ios with expo
=> update readme with total reset and multiple ios sims

src/features/school-network/JoinSchoolScreen.tsx
User reported bug: 
- If you select the second school in the list and then goto the next screen to pick the group - the name of the first school appears in the title text. 
The filter was not using equality check. Missed in code review :( 
Needs a follow up PR to change how this works for long dropdown list - but this is the smallest PR for now. 
=> Fixes passing of selected school via schoolCoordinator

src/components/Cards/EstimatedCasesMapCard.tsx
Previous we were facing this:
Fixes to this:
=> Fix android sharing

src/core/content/ContentApiClient.ts, src/core/content/ContentService.ts, src/features/register/WelcomeRepeatScreen.tsx
This PR removes the call to the backend to get AppText, which is no longer used on the UK WelcomeRepeat screen. The original intention was to allow backend driven changes to the app text.  Only Sweden and US use this - and the "defaults" in the front end are still valid. This is likely to go away soon when the welcome screens get redesigned. 
The backend APIs will be deprecated and eventually removed. 
(Hashtag Kenneth was right)
=> CHORE: Remove calls to backkend app_text API. 

src/features/AppCoordinator.ts
This builds on https://github.com/zoe/covid-tracker-react-native/pull/761 which fixes the new Dashboard screen vs the old WelcomeScreen for UK users during registration . 
For Login this issue still remains. Rather than force another server fetch on login, I'm just going to assume all UK users should see the new Dashboard screen. 
=> Fix login dashboard logic

src/core/consent/ConsentService.ts, src/features/AppCoordinator.ts
Previously the calls the the consent_status backend endpoint (which controls whether or not to ask about the Diet Study) was short circuited for Sweden and US (as there are no active studies). 
This PR changes the behaviour so:
-  for US Users it will check and display the Diet Study in the menu. 
- For US Primary Users starting an assessment flow, they will be shown an interstitial to participate in the Diet Study. 
=> Add feature flag lookup for US Diet Study

src/core/content/state/contentSlice.ts, src/core/user/dto/UserAPIContracts.ts, src/features/AppCoordinator.ts, src/features/dashboard/DashboardScreen.tsx
- Only fetch Trendline data if lad exists
- Use feature flag from BE
- Waiting on BE to be merged
=> feat(trendline): feature flag for rollout control

src/features/covid-tests/CovidTestListScreen.tsx
Moves the button placement and puts the tests within their own scroll view.
=> Bring covid test screen closer to designs

src/features/dashboard/DashboardScreen.tsx
Add a null check for startupInfo.lad which is not returned if you have an invalid postcode. 
=> Fix for null LAD for folks with an invalid 

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/components/ProfileCard.tsx, src/features/AppCoordinator.ts, src/features/ScreenParamList.tsx, src/features/menu/DrawerMenu.tsx, src/features/multi-profile/SelectProfileScreen.tsx, src/features/school-network/SchoolNetworkCoordinator.ts
This is not an ideal solution but it works. I spent quite a while looking to make it better but decided the refactoring would be too much.
The coordinator pattern is something that is very helpful for us IMO but it may need slight tweaking in future projects to get this use case to work smoothly. (Using a screen independently in 2 different flows and having the buttons call backs handled by the coordinator).
Ideally I would want to pass coordinators to a screen so it is totally decoupled from logic, however, even though this can be done, by passing a non-serializable object it has potential side effects with rebuilding state (if we were to ever do that) and also deep linking. The code in its current state might not need too much refactoring to get something like this working but I would …
=> Dont use assessment screen when selecting edit profile

assets/charts/trendline-overview.html, src/components/Stats/TrendLineChart.tsx
Increasing the trendline overview time window from weekly to monthly 
=> feat(trendline): increase overview chart time scale from 7 to 30 days

src/components/Stats/TrendLineChart.tsx
Catch empty string on trendline labels that will cause a crash:
=> Catch empty string on trendline labels 

src/core/localisation/LocalisationService.ts, src/features/AppCoordinator.ts, src/features/login/LoginScreen.tsx, src/features/multi-profile/edit-profile/EditProfileCoordinator.ts, src/features/multi-profile/edit-profile/EditProfileScreen.tsx, src/features/register/RegisterScreen.tsx, src/features/school-network/SchoolNetworkCoordinator.ts
Removes circular imports on appCoordinator, by moving the getHomeScreen function to the Localisation service.
=> Remove AppCoordinator circular dependency

src/components/Screens/share/index.tsx
Missing ref possibly causing crash: collapsable={false}
on android emulatator - this was crashing on this step
=> add missing collapsable false ref

src/features/dashboard/Header.tsx
Make the top card with the 'Report today..' button equal margin widths as below cards.
=> Report card margins

src/components/Cards/EstimatedCase/DeltaTag.tsx, src/components/Cards/EstimatedCase/TrendlineCard.tsx
font weight of change text on trendline card incorrect / changed
=> adjust font-weight for change text

src/components/Screens/share/label.tsx, src/components/Screens/share/styles.ts
When the image is shared is is converted to a .jpg, this gave the c19 logo a solid background and revealed an overlap with the blue circular background. Increased circle size to prevent this
added a linebreak to the share copy
=> add line-break and increase padding around c19 logo

src/features/covid-tests/fields/CovidTestIsRapidQuestion.tsx
Fixes incorrect field name when submitting covid tests with the new `is_rapid_test` flag.
=> Fix incorrect field name

src/features/covid-tests/fields/CovidTestIsRapidQuestion.tsx
The RapidTest Yes/No question is conditionally displayed (if the mechanism is Nasal Swab / Spit and the user has a result) - but the validation is always applied. 
This means that users cannot log a test if their result is pending. This fixes the problem by removing the validation.
**Illustration of the problem:**
=> Bug: Remove validation on Rapid Tests

assets/lang/sv-SE.json
Fixes a bug where Swedish translations strings are not in the right place in the JSON file, which means it falls back to the English text. 
Fixed version:
=> Fix Swedish translation for rapid test

src/core/api/ApiServiceErrors.ts, src/locale/utils/Locales.ts, src/storybook/stories/Selectable.stories.tsx, src/utils/async-storage-migrate.ts
@petermason raised that these can be a memory hog and are should not be in production code. 
I've left console logs in the `compare.ts` which is a test script.
=> Remove console logs

assets/icons/InfoCircle.tsx, assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/features/vaccines/VaccineDoseSymptomsScreen.tsx, src/features/vaccines/fields/DoseSymptomsQuestions.tsx
This PR changes:
- Emphasise purple title. 
- Add info text when selecting "Other"
I wanted to do something quick. Would be great to follow this up with cleaning up the use of colours / themes and to make the text bold like the design. But I'd rather not introduce another font weight in this OTA.
=> Visual Changes to Dose Symptoms Pages

src/features/vaccines/fields/VaccineDateQuestion.tsx
When the user selects a date for their first vaccination, prevent them from selecting an earlier date when choosing the second.
Example: Earlier date selection disabled.
=> prevent the selection of a date earlier that the first

src/features/vaccines/AboutYourVaccineScreen.tsx
For v2 we are no longer going to assumer PFIZER is the brand. 
A form entry will be added in v3 to allow the user to select it.
=> Stop default to PFIZER 

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, package.json, src/components/Content/ContentLoadingView.tsx, src/components/ExternalCallout.tsx, yarn.lock
Added shimmering (loading) & error state for featured content
=> feat(content-loading-state): shimmering / error message state

android/app/build.gradle, android/app/src/main/java/com/joinzoe/covid_zoe/generated/BasePackageList.java, ios/Podfile
Expo was depending on the expo-location library, however this was adding location permissions into both the iOS and android build. This lib is being installed by expo unimodules (not by us via npm/yarn) and so had to removed during the build process. Ive tested and the permission is no longer merged into the final AndroidManifest.xml. Ive also removed it on the iOS side too.
=> Remove expo-location library

src/features/patient/YourStudyScreen.tsx
- This PR renames the display name of a US Study Cohort, as requested by Andy Chan. 
- Fixes padding that was a bit of an eye sore
## After
=> Rename US Cohort

ios/Podfile.lock, src/core/Analytics.ts
Update deprecated amplitude comands
=> update amplitude commands to use async

app.json, package.json, yarn.lock
Cutting a new app store release (2.3.0 -> 2.4.0).  
The 2.3.0 release we did last week will not take any OTA updates. This appears to be because expo sdk was bumped from 39.0.0 -> 39.0.5. I have tested OTA's work with this release.
=> Downgrade to expo 39.0.0 and bump app verison (#1123)

src/features/AppCoordinator.ts, src/features/diet-study-playback/components/gut-score/index.tsx, src/features/thank-you/ThankYouUKScreen.tsx
The PR fixes a bug where are user can enter the DietStudyPlayback flow, while this.patientData is set to secondary profile. 
1) Only should the DietStudy Invite on the ThankYou page, if reporting for the primary profile. 
2) When starting the flow (which can happen from the Dashboard) with this.patientData set to secondary profiles force a reset. (This currently incurs an extra API call, which ideally should not be necessary - but requires a bigger plumbing and moving patientLists and primary patientID into redux). 
- This kind of glosses over the question of "What should this.patientData point to, when you are on the Dashboard, after just finishing with reporting for a secondary profile. This is MUCH bigger re-architecture.
=> Bug Fix for Diet Study Feedback Crashes

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/components/Cards/ShareVaccineCard.tsx, src/components/Screens/share/container.tsx, src/components/Screens/share/index.tsx, src/features/dashboard/DashboardScreen.tsx, src/features/dashboard/DashboardUSScreen.tsx
Uses the "overlay share screen" to share vaccine banner as the expo share didn;t work on device. We know this one does, so have added some options to reuse minus the wrap/label.
> share
=> Updated homepage vaccine share to use current share system

assets/lang/sv-SE.json
Adds a missing translation key
=> Adding Swedish translation for hesitancy "I do not know yet" option

src/components/icons/Icon/selection.json, src/components/icons/types/index.ts, src/features/AppCoordinator.ts, src/features/dashboard/DashboardScreen.tsx, src/features/mental-health/partials/questions/changes-question.tsx
* change equals icon
* add missing icon
* remove start screen
* add delay of 800ms to pop up
NOTE icon font has been updated at https://github.com/zoe/covid-symptoms-study-assets, you will need to pull these to test locally
=> add missing icon, delay pop up, remove start screen

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/core/state/mental-health/history/slice/index.ts, src/core/state/mental-health/history/types/index.ts, src/core/state/mental-health/learning/slice/index.ts, src/core/state/mental-health/learning/types/index.ts, src/features/mental-health/MentalHealthApiClient.ts, src/features/mental-health/MentalHealthInfosRequest.ts, src/features/mental-health/data/history.ts, src/features/mental-health/data/learning.ts, src/features/mental-health/screens/MentalHealthHistory.tsx, src/features/mental-health/screens/MentalHealthLearning.tsx
Adding free text field for mental health history and learning screens.
requires field from BE PR https://github.com/zoe/covid-app/pull/409 
Other not ticked (no text box):
Placeholder EG:
Active inputs for both:
BE admin showing saved data:
=> Other free text fields for mental health

src/features/ScreenParamList.tsx, src/features/vaccines/VaccineListMissingModal.tsx, src/features/vaccines/VaccineListScreen.tsx
Passes vaccine and not patient data to edit vaccine from via modal.
note - showPopup is called when vaccine exists but has errors, so doesn't need an ? check on it there.
**HOW TO TEST:**
on local / staging, create a valid vaccine. 
Access the valid vaccine in the Django Admin: http://127.0.0.1:8000/admin/vaccines/dose/ 
Set the date and/or name to empty & save
On the app, go back and return to the vaccine list page (to reload state)
Tap the next button at the bottom: modal should appear
Modal should link to your [first] vaccine, in edit mode
=> Vaccine edit modal fix

src/features/mental-health/screens/MentalHealthChanges.tsx
After the `MentalHealthStart` screen was removed from the screen flow the `createNewMentalHealthRecord()` was never called. 
This PR now calls this code on the `MentalHealthChange` screen. (This is the first screen after the user elects to start the study from the modal).
=> Create Mental Health Record

src/features/mental-health/screens/MentalHealthHistory.tsx
This corrects (and simplifies) the screen routing, to always navigate to `MentalHealthSupport`
From `MentalHealthHistory` the next screen has conditional logic:
if Yes -> Next Screen is `MentalHealthSupport` followed by `MentalHealthLearning`
if no / prefer not to stay -> `MentalHealthLearning` (skipping MentalHealthSupport)
`MentalHealthHistory` -> `MentalHealthSupport` -> `MentalHealthLearning`
---
There's been some lost in translation from spec -> figma -> code. 
Something to discuss in the retro!!
=> Fix to mental health routing

package.json, src/components/BrandedButton/__tests__/BrandedButton.test.tsx
Mucked around with fixing tests, then did a bit of research and upgraded packages. Reinstated several tests on BrandedButton & plan to write logic/test for "singleUse" - maybe not on Branded button though (would require some thought on state etc).
Getting this PR up for clarity between me/peters coincidental test fixing!
=> Upgrade and reinstate tests

src/features/AppCoordinator.ts
If you navigate to the DietScores Feedback v2 (New Flow) after reporting for a secondary profile, it keeps the PatientData of the secondary profile (which of course has no scores). This causes an error / wrong scores to appear. 
This is a surgical fix to the v2 flow that was already applied to the v1 flow:
https://github.com/zoe/covid-tracker-react-native/commit/abb183a377bb5e87839dd1815bcbe6cbb02a7868
Sadly... DRY
=> Fix incorrect patientData on DietScores v2 flow

src/core/vaccine/dto/VaccineRequest.ts, src/features/vaccines/AboutYourVaccineScreen.tsx, src/features/vaccines/components/VaccineCard.tsx, src/features/vaccines/fields/VaccineNameQuestion.tsx
- This PR separates out the vaccines brand options between UK, SE and US instead of using splice for clarity
- Add's the J&J vaccine option for the US
- Hides the second dose on the Vaccine Card (List Display) and on the "AboutYourVaccine" screen (Create / Edit Vaccine)
This PR works with the fact that all the vaccine code was written with the assumption of 2 doses, rather than try to addrss that assumption.  When we get another vaccine with either 1 dose or 3 doses then we should refactor. For now and "if vaccine.brand == johnson"
=> Add Johnson Vaccine for US

src/features/vaccines/VaccineListScreen.tsx
This PR disables the vaccine banner temporarily. 
Whilst this works on simulator, we get an error in the AppCenter builds to do with hooks. 
By disabling this for now it unblocks rolling out the `develop` to production #1199 (URGENT!) and #1200
=> Disable vaccine banner

src/features/anniversary/screens/anniversary-modal.tsx
Updates the timeline modal's date placeholder to use the date from the current user - assumed that this is the core user as it happens on app start
kind of confusing that the screenshot says feb... 3,2,1... design critique incoming ! :)
no
=> Set user signup date from profile for timeline modal

src/features/dashboard/DashboardScreen.tsx, src/features/dashboard/DashboardUSScreen.tsx, src/features/diet-study-playback/v2/DietStudyModal.tsx, src/features/thank-you/ThankYouUKScreen.tsx, src/features/thank-you/ThankYouUSScreen.tsx
This PR:
- Removes the Mental Health Study popup. This will effectively mean there is no other way to access the mental health study. We'll keep the code in here, as we might run this again in the future. 
- Removes the UK Diet Scores card from the UK Thank You page. You'll be able to get here via the Timeline Screen.
=> Remove Mental Health Study Entry Point

src/features/anniversary/partials/timeline.tsx, src/features/anniversary/types/index.ts
The old timeline json format had an extra level of nesting that doesn't seem to serve any purpose. This nesting is no longer there in the new backend code.  
Old: 
```
"items": [
{
node:  {
"title": "SIGNED UP",
"date": "2020-03-10",
"event_type": "NODE",
"sub_title": "You started reporting!",
"summary": null,
"route_name": null,
"route_text": null,
"external_link": null,
"external_link_text": null,
"ongoing": null,
"progress": null,
"your_contribution": null
},
},   
]
```
New: 
```
"items": [
{
"title": "SIGNED UP",
"date": "2020-03-10",
"event_type": "NODE",
"sub_title": "You started reporting!",
"summary": null,
"route_name": null,
"route_text": null,
"external_link": null,
"external_link_text": null,
"ongoing": null,
"progress": null,
"your_contribution": null
},
]
```
=> Change json format of timelines

package.json, yarn.lock
A whole bunch of sub-dependencies are included because on react-native-web which keep hitting security advisories. 
This PR
- Removes react-native-web as a top level dependency
- Updates sub-dependencies
This solves the following security issues:
- https://github.com/zoe/covid-tracker-react-native/security/dependabot/package-lock.json/y18n/open
- And `xmlDom 0.5.0`
=> Remove react-native-web and update sub-dependencies

src/components/messaging/banners/styles.ts
Dimensions.get('window') returns 400 (number). This is passed into SContatinerView. Which uses it to set the width, but it needs units. 
```
function Banner({ active = true, message }: IProps) {
...
const { width } = Dimensions.get('window');
...
<SContainerView top={top} width={width} style={{ transform: [{ translateY: animateTo }] }}>
```
=> Fix warning about missing units

.circleci/config.yml, src/components/Cards/EstimatedCasesMapCard.tsx, src/components/Screens/share/container.tsx
[1] This PR fixes the error you get on device only (it's fine in the simulator) when you try and share the Personalised map card. 
Here's the error:
Here is it working:
[2] Also fixes a missing prop on the ShareVaccineCard
=> Fix Map Sharing

src/core/push-notifications/PushNotificationService.test.ts, src/core/push-notifications/PushNotificationService.ts, src/utils/datetime.ts
Start refreshing the pushing notifications on the server faster. Charlie suggests checking every time the app starts is no bad thing. 
Woo: Nice to have unit tests!
=> Set push tokens to refresh daily

src/features/diet-study-playback/v2/DietStudyCard.tsx
Removes inconsistent drop shadow on the DietScore card on the homepage.
=> Remove inconsistent shadows

android/app/src/main/AndroidManifest.xml, app.json, ios/Covid/Info.plist, package.json, src/CovidApp.tsx
[1] Fixes the `scheme` attribute which cannot have hyphens
[2] Upgrade app store release from 2.4.0 -> 2.5.0
=> Fix Schema and bump app version

ios/Covid/Info.plist, src/core/VersionUpdateModal.tsx
Switch to using deep links on the pop up that forces users to upgrade to the latest version. 
Inspired by this Stack Overflow:
https://stackoverflow.com/questions/62445835/how-to-open-directly-our-app-in-apple-store
=> Switch to using deep links

android/app/src/main/AndroidManifest.xml, ios/Covid/covid-zoe.entitlements
Following the instructions in here https://docs.expo.io/guides/linking/#universaldeep-links-without-a-custom-scheme to add Permissions for a universal link served from https://api.covidjoinzoe.com/launch/ to launch the app.
=> Add universal link permissions

src/core/user/dto/UserAPIContracts.ts, src/features/assessment/HowYouFeelScreen.tsx
Rollout handling for long covid. This is done on a per-account (User) and not Profile, hence using StartupInfo on the HowYouFeelScreen
BR ticket: https://github.com/zoe/covid-app/pull/485
=> Long covid rollout strategy

src/components/Modal.tsx, src/core/VersionUpdateModal.tsx, src/core/state/settings/slice/index.ts, src/core/state/settings/types/index.ts, src/features/anniversary/screens/AnniversaryModal.tsx, src/features/dashboard/DashboardScreen.tsx, src/features/diet-study-playback/v2/DietStudyModal.tsx, src/features/mental-health-playback/MentalHealthPlaybackModal.tsx, src/features/mental-health/screens/MentalHealthModal.tsx
This PR removes the existing modal events sent to our backend on every view of every modal. It's replaced with two specific events that are called when the Mental Health Playback modal (the only currently active modal) is interacted with. (View Insights or Skip Insights).
=> Modal Events

src/core/Analytics.ts, src/core/content/ContentService.ts, src/features/AppCoordinator.ts, src/features/dashboard/DashboardScreen.tsx, src/features/dashboard/DashboardUSScreen.tsx, src/features/register/WelcomeRepeatScreen.tsx
- Remove the Analytics.identify() call on each of the dashboards and move it into the app initialisation code. 
- Send the MHIP Cohort from startup_info to Amplitude
=> Identify experiment cohort

src/features/long-covid/screens/consts.questions.tsx
Sets dropdown for symptom change default to not applicable. this value is passed, by default, to BE unless changed (see data dump)
=> Long covid 'NOT_APPLICABLE' defaults

.gitignore, src/features/vaccines/fields/VaccineNameQuestion.tsx
- Add J&J to UK vaccine list of options.
- https://www.notion.so/joinzoe/Add-J-J-Vaccine-for-the-UK-53f5e303df8f47c6bd87473c081a4470
iOS
Android
- I'm going to make a small amend to the Typescript in a follow up PR because I noticed some Typescript errors in the file I changed (which were already present prior to my changes). There also seems to be related typescript errors in other files, so not sure whether my Typescript "fix" will have repercussions? If anyone has reservations, then LMK.
=> Add J&J vaccine to UK list 

src/core/content/state/contentSlice.ts
Caused by a mix of sync and async in the ContentService service. Have created a ticket to refactor the service completely ( https://www.notion.so/joinzoe/Refactor-ContentService-7ea01969fff54f8299d53f95f05dcb6d )
Issue caused by these two bits:
https://github.com/zoe/covid-tracker-react-native/blob/develop/src/core/content/ContentService.ts#L33
https://github.com/zoe/covid-tracker-react-native/blob/develop/src/core/content/ContentService.ts#L107
=> Startup graph sync issue

src/components/TextareaWithCharCount.tsx, src/components/index.ts, src/features/assessment/TreatmentOtherScreen.tsx, src/features/assessment/fields/OtherSymptomsQuestions.tsx, src/features/long-covid/screens/LongCovidQuestionPageOne.tsx, src/features/mental-health-playback/screens/MHPRatingScreen.tsx, src/features/vaccines/VaccineDoseSymptomsScreen.tsx, src/features/vaccines/fields/DoseSymptomsQuestions.tsx
- Extract out `Textarea` with character count to a new component called `TextareaWithCharCount`
- Replace existing `Textarea` components throughout app with new component
- Ticket: https://www.notion.so/joinzoe/Refactor-TextArea-Component-with-Character-Limit-9ae797d55e494daba21787c5aea9c542
Should be part of Formik refactor as there's probably an opportunity to standardise how this looks throughout the app.
=> Replace Textarea component with TextareaWithCharCount component

src/features/password-reset/ResetPasswordScreen.tsx
Adds a back button to forgot password screen 
=> Back button for forgot password screen

src/components/DropdownField.tsx
Restored the min dropdown height.
I wanted to do a bit of smarter work to handle content better, but am in fear of causing regressions! Let's replace this entire widget with one that automatically calculates its height (there's already a ticket).
Ticket mentioned above to replace widget
=> Reverted dropdown min height

src/features/password-reset/fields/ResetPasswordForm.tsx
- Add form validation to ResetPasswordForm.
- No specific ticket, logging finished refactors here: https://www.notion.so/joinzoe/Fun-with-Forms-d66ad33a88694d8aaa86777fbf4a75b8#22636d7c049b4132a051c3a5eea4b8fc
=> Add required validation to ResetPasswordForm

src/features/multi-profile/edit-profile/EditLocationScreen.tsx
- Add form validation to EditLocationForm.
- No specific ticket, logging finished refactors here: https://www.notion.so/joinzoe/Fun-with-Forms-d66ad33a88694d8aaa86777fbf4a75b8#22636d7c049b4132a051c3a5eea4b8fc
=> Add required validation to EditLocationForm

src/features/covid-tests/CovidTestDetailScreen.tsx, src/features/covid-tests/fields/CovidTestDateQuestion.tsx, src/features/covid-tests/fields/CovidTestInvitedQuesetion.tsx, src/features/covid-tests/fields/CovidTestIsRapidQuestion.tsx, src/features/covid-tests/fields/CovidTestLocation.tsx, src/features/covid-tests/fields/CovidTestMechanismQuestion.tsx, src/features/covid-tests/fields/CovidTestResultQuestion.tsx
- Add form validation to CovidTestDetail form.
- No specific ticket, logging finished refactors here: https://www.notion.so/joinzoe/Fun-with-Forms-d66ad33a88694d8aaa86777fbf4a75b8#22636d7c049b4132a051c3a5eea4b8fc
=> Refactor CovidTestDetail form for form validation

src/features/patient/AboutYouScreen.tsx
Fixes the error state for "About you" form on back.
Note that this form, and others, should be refactored to be functional components, in which case we can better handle any back/navigation events with useEffect.
https://www.notion.so/joinzoe/017c3de591604a7b89d0b69e3c37b279?v=0133357df3ed42e1bd42c1e0d7afcf45&p=b928c836e318483aa47ff045eb9417a3
=> Fixed About you form back error

src/features/assessment/HealthWorkerExposureScreen.tsx, src/features/vaccines/AboutYourVaccineScreen.tsx
1. Do not show errors immediately upon "yes" being selected during daily assessment of health worker who has seen a patient in the last day.
2. Button now enabled immediately if user edits and existing vaccine.
n/a
n/a
=> Fix a couple of form refactor bugs upon testing on staging

src/features/patient/PreviousExposureScreen.tsx
Add required props to the PreviousExposure to COVID form.
Need to refactor to a functional component so that we can reset the form if a user clicks back on navbar after submitting. 
Ticket: https://www.notion.so/joinzoe/Product-Eng-Board-ca9e8b1b8926481f8c94cb01a88d567d?p=5c5011dd2c9f4b86a01f1db55820f8bd
=> Add required prop to fields in PreviousExposure form

.circleci/config.yml
This was introduced as a clean slate for the detox build, but is not needed without it and is causing the ota cache error.
=> Removed yarn metro-empty-cache from circle ci build script

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/features/AppCoordinator.ts, src/features/reconsent/components/ReconsentScreen.tsx, src/features/reconsent/screens/ReconsentRequestConsentScreen.tsx
Notion: https://www.notion.so/joinzoe/Re-consent-Flow-Request-Consent-screen-4th-screen-04f7a2e89a54477baa11795f257d0f0e
Notes:
- Have asked Sol about new copy for Privacy Policy. We'll probably need to create a new route for this.
- Didn't use `FlatList` to render callout boxes as thought it was a bit overkill in this case. :)
- I've allowed the subtitle to fill the width of the screen (goes against Figma designs). Do we have a rule on this / how do we deal with different screen sizes?
n/a
=> Reconsent Flow - Request consent confirmation screen

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/features/reconsent/screens/ReconsentDiseasePreferencesScreen.tsx
Refactor:
- Move copy to translation files
- Use the `ReconsentScreen` wrapper
https://www.notion.so/joinzoe/Product-Eng-Board-ca9e8b1b8926481f8c94cb01a88d567d?p=e1aa34fff0c54f7f8a49df052e13a990
=> DiseasePreferences Screen: Move copy to translation files and use ReconsentScreen wrapper

src/core/state/reconsent/slice/__tests__/index.ts, src/core/state/reconsent/slice/index.ts, src/core/state/reconsent/types/index.ts, src/core/state/root.ts, src/core/user/dto/UserAPIContracts.ts, src/features/reconsent/screens/ReconsentDiseasePreferencesScreen.tsx, src/features/reconsent/screens/ReconsentDiseaseSummaryScreen.tsx, src/features/reconsent/screens/ReconsentRequestConsentScreen.tsx
https://www.notion.so/joinzoe/Re-consent-Flow-Use-Formik-state-to-manage-disease-preferences-d2e26c534ea143a385f044a09e4aeefc
https://www.notion.so/joinzoe/Product-Eng-Board-ca9e8b1b8926481f8c94cb01a88d567d?p=5cd3749b554c4dfbaad17d5e1667a59f
n/a
Wait for backend migrations to check that disease preferences are being saved.
=> Restructuring "reconsent" slice and save disease preferences to backend

src/features/reconsent/screens/ReconsentNewsletterSignupScreen.tsx
This is due to the sequence of when the component state is saved vs when the boolean is sent to the backend!
=> Fix the boolean being sent to the backend for the newsletter signup

assets/lang/en.json, assets/lang/es.json, assets/lang/sv-SE.json, src/features/reconsent/screens/ReconsentDiseaseSummaryScreen.tsx
https://www.notion.so/joinzoe/Re-consent-flow-Amend-copy-on-summary-screen-if-no-diseases-are-selected-Sol-to-provide-cb6feb3c8abe45b4a8ad949d191429d7
=> Update copy on summary screen if no diseases are chosen

src/core/user/dto/UserAPIContracts.ts, src/features/dashboard/DashboardScreen.tsx
Only show the reconsent flow on startup if the `show_research_consent` flag is true.
=> Show reconsent flow based on show_research_consent flag

package.json, src/features/dashboard/DashboardScreen.tsx, src/features/thank-you/ThankYouUKScreen.tsx, yarn.lock
- Moved the reconsent starting point to the home screen
- Sub dependency `Immer` updated by dependabot
=> 2.6.0-ota-6

assets/lang/en.json, assets/lang/sv-SE.json, src/components/Text.tsx, src/features/reconsent/screens/ReconsentRequestConsentScreen.tsx, src/features/vaccines/VaccineListScreenUpdated.tsx
- Add clarification copy that user is only re-consenting for the primary user
- Save disease preferences in the event that no consent is provided
- Finish styling of info modal for new vaccine screens (informing user of ability to log vaccines as part of a trial)
=> OTA release 2.6.0

src/components/CalloutBox.tsx, src/features/register/WelcomeRepeatScreen.tsx
- Bugfix for Swedish users for which the menu icon was not visible anymore on the home screen.
=> 2.6.0-ota-21

src/components/cards/estimated-case/TrendlineCard.tsx, src/core/content/ContentApiClient.ts, src/core/content/ContentService.ts, src/features/AppCoordinator.ts, src/features/ScreenParamList.tsx, src/features/dashboard/TrendlineScreen.tsx, src/features/multi-profile/edit-profile/EditLocationScreen.tsx
- Fix for the not matching covid cases number with graph data.
=> 2.6.0-ota-25
