mock-server/mockServer.ts
src/core/user/dto/UserAPIContracts.ts
src/features/patient/YourStudyScreen.tsx

Adds a new cohort to the list of US studies shown after a participant completes US Research consent.

Add US Black Women's Health Study cohort

---

assets/lang/en.json
src/core/AsyncStorageService.ts
src/core/user/UserService.ts
src/core/user/dto/UserAPIContracts.ts
src/features/SplashScreen.tsx
src/features/register/CountryIpModal.tsx
src/features/register/gb/WelcomeScreen.tsx
src/features/register/us/Welcome2USScreen.tsx

The first time a user tries to create an account we will check their ip against the selected country in app. If these do not match we popup a modal asking them to confirm their country.

Check user ip against locale when creating account

---

src/features/assessment/StartAssessment.tsx

Users without a profile should go to YourWork not the AboutYou screen as it comes it.

Users without a profile should go to YourWork.

---

src/components/DaysAgo.tsx
src/features/ScreenParamList.tsx
src/features/multi-profile/AdultOrChildScreen.tsx
src/features/multi-profile/ConsentForOtherScreen.tsx
src/features/multi-profile/CreateProfileScreen.tsx
src/features/multi-profile/ReportForOtherScreen.tsx
src/features/multi-profile/SelectProfileScreen.tsx
src/features/near-you/NearYou.tsx
src/features/register/us/TermsOfUseScreen.tsx

[1] CreateProfile screen needs to take in avatarName as a routeProp. This is probably a merge issue
[2]  Fix fetching patientID from response to POST to patient API
[3] Change ScreenParamList for NearYou screen.
[4] Improves the text displayed to "Today", "Yesterday", "x days ago" or "Never Reported"
[5] Fix Back button on US TermsOfUse Screen

Report for Others Bug Fixes and Layout Updates

---

src/components/DaysAgo.tsx
src/core/AsyncStorageService.ts
src/core/user/UserService.ts
src/features/Navigation.ts
src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/LevelOfIsolationScreen.tsx
src/features/assessment/TreatmentOtherScreen.tsx
src/features/assessment/TreatmentSelectionScreen.tsx
src/features/assessment/WhereAreYouScreen.tsx
src/features/multi-profile/ReportForOtherScreen.tsx

Adds an extra screen prompting user to log for another, if they haven't done so already.

Add extra screen prompting user to log for another.

---

src/features/multi-profile/ConsentForOtherScreen.tsx
src/features/multi-profile/SelectProfileScreen.tsx

Reset navigation stack on Create/Select Profile

Reset navigation stack on Create/Select Profile

---

src/components/PatientHeader.tsx
src/components/Screen.tsx
src/features/assessment/CovidTestScreen.tsx
src/features/assessment/DescribeSymptomsScreen.tsx
src/features/assessment/HealthWorkerExposureScreen.tsx
src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/LevelOfIsolationScreen.tsx
src/features/assessment/TreatmentOtherScreen.tsx
src/features/assessment/TreatmentSelectionScreen.tsx
src/features/assessment/WhereAreYouScreen.tsx
src/features/multi-profile/SelectProfileScreen.tsx
src/features/patient/AboutYouScreen.tsx
src/features/patient/YourHealthScreen.tsx
src/features/patient/YourStudyScreen.tsx
src/features/patient/YourWorkScreen.tsx

Add back button to Patient Header

---

assets/lang/en-US.json
assets/lang/en.json
src/features/assessment/DescribeSymptomsScreen.tsx
src/features/assessment/HealthWorkerExposureScreen.tsx
src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/LevelOfIsolationScreen.tsx
src/features/assessment/TreatmentOtherScreen.tsx
src/features/assessment/TreatmentSelectionScreen.tsx
src/features/assessment/WhereAreYouScreen.tsx

This PR:
- Ensures all user-facing strings on assessment screens are localized.
- Ensures text on TreatmentOtherScreen changes depending on whether the treatment is current or historic.

Ensure strings are localized (part 2: assessment screens)

---

app.json
src/core/user/UserService.ts

Notch the version numbers for the next release. Will merge into develop when we are ready to build, after QA have given the thumbsup.

Prod release: 0.12, doc versions: 1.3.0

---

assets/lang/en-US.json
assets/lang/en.json
src/features/login/LoginScreen.tsx
src/features/password-reset/ResetPassordConfirm.tsx
src/features/password-reset/ResetPassword.tsx
src/features/register/ConsentScreen.tsx
src/features/register/OptionalInfoScreen.tsx
src/features/register/RegisterScreen.tsx
src/features/register/gb/WelcomeRepeatScreen.tsx
src/features/register/gb/WelcomeScreen.tsx
src/features/register/us/BeforeWeStartUS.tsx
src/features/register/us/Welcome1USScreen.tsx
src/features/register/us/Welcome2USScreen.tsx

[1] Extracts i18n strings from :
- Register Components
- Login 
- Password Reset
[2] Fixes capitalisation on buttons on Consents Pages
[3] Minor layout updates on Password Reset and Login Page

Extract i18n Strings Part 3 (Welcome + Register / Login + Password Reset)

---

package-lock.json
package.json
tests/empty.spec.ts

There were merge conflicts in the package lock file, so I've created a clean PR from develop based off @rogoodheadTAB's PR: https://github.com/zoe/covid-tracker-react-native/pull/69/

Switch to jest testing framework

---

mock-server/mockServer.ts

Add missing endpoints to mock server:
* `/users/startup_info/`
* `/patient_list/` -- which now returns Me, Alice and Bob.
Which allows a developer to at least get to the SelectProfile screen.

Update mock server

---

assets/lang/en.json
src/features/multi-profile/SelectProfileScreen.tsx

Visual changes to Select Profile screen requested by Elana
- Changed "Never reported" to "Not reported
- Truncate Profile name by clamping to 1 line
- Add menu icon

Visual changes to SelectProfile Screen

---

assets/lang/en.json
assets/lang/sv-SE.json

And added "sweden" to the English file.

add swedish translation file

---

src/components/ProgressStatus.tsx

Fixes https://github.com/zoe/covid-tracker-react-native/issues/91

fix(Progress Loader): Fix progress loader height

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
docs/pull_request_template.md

_Please attach screenshots showing the change if relevant _ 

docs(Linting): Fix linting on documentation

---

package.json

Add package command to clean local git branches and delete ones no longer present on remote - this works with forks too.
There are no follow up tasks required

chore(Local env): Add command to clean local git branches

---

src/features/register/Welcome1Screen.tsx

This PR fixes the button being outside the scrollable view and unavailable on US, this also affects UK and Sweden
Before:
After:
Unit tests should be added

fix(WelcomeScreen): Fix welcome screen scroll view

---

assets/lang/en.json
assets/lang/sv-SE.json
src/CovidApp.tsx
src/features/ScreenParamList.tsx
src/features/register/ConsentScreen.tsx
src/features/register/LegalComponents.tsx
src/features/register/constants.ts
src/features/register/gb/PrivacyPolicyUKScreen.tsx
src/features/register/sv/PrivacyPolicySVScreen.tsx

The new swedish consent flow:
- swedish consent
- privacy policy
- refactored consent screen.
- new document versions
Look into using a markdown renderer if we feel that updating the legal docs is becoming a large time investment - the 2-3 legal components I have made are one-offs in that they're built for fast copy pasting and condensing large swathes of text.

SWEDEN consent flow 4

---

assets/lang/en.json
src/features/assessment/WhereAreYouScreen.tsx

Fix various copy issues and inconsistencies  - fix #164

Fix various copy issues and inconsistencies

---

src/features/register/ConsentScreen.tsx
src/features/register/sv/PrivacyPolicySVScreen.tsx

Fix Email in Swedish consent
Potential re-evaluations of emails depending on responses

Fix Email in Swedish consent

---

app.json

Notch version numbers in preparation for a new build

increment version, buildNumber and versionCode.

---

assets/lang/sv-SE.json

use Lund university website in share module

---

src/features/assessment/StartAssessment.tsx

Fix back dated questions conditional

---

src/core/user/dto/UserAPIContracts.ts
src/features/patient/YourStudyScreen.tsx

8 new additions to US cohorts. Also a reordering of the cohort list.
Requires this backend PR to be live before merging this into develop: https://github.com/zoe/covid-app/pull/151

Add 8 new US cohorts

---

src/features/patient/YourWorkScreen/helpers.ts
src/features/patient/YourWorkScreen/index.tsx

Disabled button CTA on Your Work screen if required fields aren't filled in - issue #195

feature(YourWorkScreen): Button CTA disabled 

---

src/features/assessment/CovidTestScreen.tsx

add default to know-date-of-test

---

src/features/SplashScreen.tsx
src/features/login/LoginScreen.tsx

Fix imports on Splash Screen

---

src/features/register/gb/PrivacyPolicyUKScreen.tsx
src/features/register/sv/PrivacyPolicySVScreen.tsx
src/features/register/us/PrivacyPolicyUSScreen.tsx

Sweden: text changes, new paragraphs, and fixing some display issues
UK & US: Update list of third-party processors

Update privacy policies

---

.circleci/config.yml

Fixes bad fastlane command
None :(

Update fastlane command

---

src/features/patient/fields/HormoneTreatmentQuestion.tsx
src/features/patient/fields/RaceEthnicityQuestion.tsx

When selecting from the multi-select options, selecting None or Prefer Not to say, should de-select the other options.
Unable to demonstrate via a ss
No

Update multiselect logic

---

assets/lang/en.json
assets/lang/sv-SE.json
src/features/assessment/LevelOfIsolationScreen.tsx

Update Healthcare Worker question to specify that patients are being treated in person 
Fix missing FormikProps import

Update Healthcare Worker question + fix import

---

src/core/user/UserService.ts

Increment assessment version for OTA

Increment assessment version

---

src/features/login/LoginScreen.tsx

This is a temporary fix to hide the spinner on the login screen. This will be superseded by https://github.com/zoe/covid-tracker-react-native/pull/227 soon. 

Temp fix for spinner on Login Screen

---

assets/lang/sv-SE.json
src/features/patient/fields/PeriodFrequencyQuestion.tsx
src/features/patient/fields/PeriodQuestion.tsx

Due to the initialisation of i18n, we need to move the items drop down definition. 

Fix Swedish translations

---

src/core/user/UserService.ts
src/features/assessment/ProfileBackDateScreen.tsx

On backfill, apply feature.showRaceQuestion to state

---

app.json

Prepare app.json for new app build, to change the name of the app.

prepare 0.13.2 app build.

---

assets/lang/en.json
assets/lang/sv-SE.json
src/features/patient/fields/PeriodQuestion.tsx

add not-currently to period list.

---

src/core/user/UserService.ts

Increment PatientVersion -- added a new period option: not_currently.

notch patient version for additional option in period status question.

---

assets/lang/sv-SE.json

accidentally overwrote this change in a commit to another PR

add swedish placeholder translation

---

assets/lang/en.json

Fixing a typo in the donation module.

fix typo in donation module

---

src/core/patient/PatientState.ts
src/core/user/UserService.ts
src/features/assessment/ProfileBackDateScreen.tsx
src/features/assessment/StartAssessment.tsx
src/features/patient/AboutYouScreen.tsx

Fix for logic and rename variable to make it less confusing. Unfortunately we are using the same backend variable for 2 slightly different things so it cant be perfectly simple but I hope this is better.

Fix race backfill logic

---

src/features/assessment/CovidTestDetailScreen.tsx

Due to the relatively low numbers of people who have duplicates, and the amount of duplicates per person (most are 3 or less duplicates). This seems to be an issue of frustrated button tapping when the servers are unresponsive.
This fix stops the sending of tests multiple times if the button is tapped more than once.

Stop multiple submit taps for adding tests

---

assets/icons/Check.tsx
package.json
src/components/Checkbox.tsx
src/features/multi-profile/ConsentForOtherScreen.tsx

Issue #231
update checkbox style and add react-native-svg

Issue#231 update checkbox style and add react-native-svg

---

assets/lang/sv-SE.json

Adds the translations associated with #277

Add Swedish translations for errors

---

src/components/Checkbox.tsx

Fixes wrapping of multi-select text

Fixes wrapping of multi-select text

---

src/components/CalloutBox.tsx
src/core/ContentService.ts
src/features/register/WelcomeRepeatScreen.tsx

Create a component to render a CalloutBox -- a component that will evolve to get it's content from the backend.

Create CalloutBox for WelcomeRepeat screen

---

src/components/Screen.tsx
src/features/assessment/DescribeSymptomsScreen.tsx
src/features/assessment/HealthWorkerExposureScreen.tsx
src/features/assessment/LevelOfIsolationScreen.tsx
src/features/patient/AboutYouScreen.tsx
src/features/patient/PreviousExposure.tsx
src/features/patient/YourHealthScreen.tsx
src/features/patient/YourStudyScreen.tsx

Move keyboard avoiding view up into screen object to wrap the scroll view. When it was nested it wasn't working.
Main changes in the Screen file. The other changes are removing the lower level keyboard avoiding view and then reformatting.
The Screen component needs a general fix up. We need to not wrap everything in a scroll view and also handle the header navigation better.

Fix keyboard above input fields

---

.circleci/config.yml

Using the last argument as keyword parameters is deprecated; this fixes that

switch parameter convention

---

.circleci/config.yml
fastlane/Fastfile

Revert #307 and ACTUALLY fix the error this time :)

Fix fastlane ci 2

---

assets/index.ts
assets/lang/en.json
assets/lang/sv-SE.json
src/CovidApp.tsx
src/core/user/UserService.ts
src/core/user/dto/UserAPIContracts.ts
src/features/Navigation.ts
src/features/ScreenParamList.tsx
src/features/multi-profile/SelectProfileScreen.tsx
src/features/register/gb/ValidationStudyConsentScreen.tsx
src/features/register/gb/ValidationStudyIntroScreen.tsx

Add intro and validation screens but navigation and posting to the backend is incomplete

Validation study intro and consent

---

src/features/register/gb/ValidationStudyConsentScreen.tsx

Update validation study consent text

Update consent text

---

assets/lang/en-GB.json
assets/lang/en.json
assets/lang/sv-SE.json
src/CovidApp.tsx
src/features/assessment/CovidTestDetailScreen.tsx
src/features/register/gb/ValidationStudyConsentScreen.tsx

Updates the copy and adds the header. Header needed as no obvious way to back out of consent on iOS otherwise.

Validation Study copy update

---

assets/lang/en-GB.json
src/features/register/gb/ValidationStudyIntroScreen.tsx

Styling on validation study screen

Fix styling

---

src/components/DropdownField.tsx
src/features/patient/AboutYouScreen.tsx

Part 1 of Field Stylings update #230 
Android
No error - before & after
Error - before & after
iOS
No error - before & after
Error - before & after

Dropdown ux

---

src/features/register/gb/ValidationStudyConsentScreen.tsx

Makes necessary edits to the PIS after review by KCL Ethics team.
Version number has been deliberately not bumped.

Update Validation Study PIS v3 copy

---

src/core/Analytics.ts
src/core/user/UserService.ts
src/features/register/constants.ts
src/features/register/gb/ValidationStudyConsentScreen.tsx
src/features/register/gb/ValidationStudyIntroScreen.tsx

Cherrypicks 2 PRs
- Adds Analytics to Study Consent Screens
- Updates Ethics Approval Text to v3

Hotfix OTA Release

---

src/features/register/gb/ValidationStudyIntroScreen.tsx

Add bottom padding to ValidationStudyIntro screen

---

src/features/assessment/DescribeSymptomsScreen.tsx
src/features/patient/AboutYouScreen.tsx
src/features/patient/fields/HeightQuestion.tsx
src/features/patient/fields/WeightQuestion.tsx

Refactors out Height + Weight Questions into their own components. 
Should make potential future work with backdating these fields easier.

Refactor Height + Weight Questions

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/assessment/ProfileBackDateScreen.tsx
src/features/patient/YourHealthScreen.tsx
src/features/patient/fields/VitaminQuestion.tsx

Adds text to add justification for the new question.
Also uses custom error message that can be translated.
Refactoring checkbox fields into a re-usable field. Too much messy overhead around them atm.
Add optional justification label to existing dropdown + text fields

Vitamin justification

---

src/features/register/gb/ValidationStudyConsentScreen.tsx

Small PR for copy and button alignment on Validation Study Consent

Update button copy on consent screen and padding

---

src/components/GenericTextField.tsx
src/features/patient/AboutYouScreen.tsx
src/features/patient/YourWorkScreen/index.tsx
src/features/patient/fields/HeightQuestion.tsx
src/features/patient/fields/VitaminQuestion.tsx
src/features/patient/fields/WeightQuestion.tsx

- Fixes errors being shown on Your Work and About You screen before submission. 
- Adds check on formik props.touched and formik submitCount > 0

Fix showing errors before submission

---

src/components/ShareThisApp.tsx
src/features/ThankYouScreen.tsx

- Remove unused prop on Share Module. 
- Fix imports

Cleanup Share Module

---

src/features/Navigation.ts
src/features/assessment/AssessmentCoordinator.ts
src/features/multi-profile/ReportForOtherScreen.tsx

Refactors duplicate code in the Navigatior.ts and AssessmentCoordinator to get the ThankYouScreen. 

Refactor getThankYouScreen function

---

src/features/assessment/DescribeSymptomsScreen.tsx
src/features/assessment/ProfileBackDateScreen.tsx
src/features/patient/PreviousExposure.tsx
src/features/patient/YourHealthScreen.tsx
src/features/patient/YourStudyScreen.tsx

Addresses some that were missed in previous PR .

Prevent ValidationErrors being shown before submission

---

src/features/register/gb/ValidationStudyInfoScreen.tsx

Rotation unused as its replaced with a rotated png

Remove incorrect rotation

---

src/features/ThankYouUKScreen.tsx

- Update webinar link
- Title case the utm_source so it doesn't give me anxiety when looking at GA. 
- Removes dead code

Update Webinar Link

---

appConfig.ts
src/core/assessment/dto/AssessmentInfosRequest.ts
src/features/Navigation.ts
src/features/assessment/DescribeSymptomsScreen.tsx
src/features/register/gb/ValidationStudyConsentScreen.tsx

Add in missing field to send hay-fever symptom to backend, fix typescript complaint and bump assessment and patient versions.

Missing field + minor fixes

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/core/assessment/dto/AssessmentInfosRequest.ts
src/features/assessment/DescribeSymptomsScreen.tsx

The question was asked inversed compared to all others, so we retranslated and switched it to match.

Inverse hayfever symptoms question

---

src/features/Navigation.ts

When you create a brand new profile and then join the study via the ad on the Thank You Page. you don't see the SelectProfile, which causes and issue. 
This fixes that!

Fix navigation

---

src/features/assessment/DescribeSymptomsScreen.tsx

Incorrect name set in formik field.

Fix rename of hayfever field

---

package-lock.json
package.json

Update logKitty to 0.7.1 to patch security issue:
https://github.com/advisories/GHSA-v8v8-6859-qxm4

Update logKitty dependency

---

App.tsx
README.md
package-lock.json
package.json
src/components/CenteredView.tsx
src/storybook/StorybookScreen.tsx
src/storybook/decorator.tsx
src/storybook/index.ts
src/storybook/rn-addons.ts
src/storybook/stories/AppVersion.stories.tsx
src/storybook/stories/Badge.stories.tsx
src/storybook/stories/PoweredByZoe.stories.tsx
src/storybook/stories/Spinner.stories.tsx
src/storybook/stories/VisitWebsite.stories.tsx

This PR adds Storybook and Storybook Server to the repo: https://storybook.js.org/
Storybook is a useful tool to encourage Component Based Design. 
Approach:
- I've chosen to put a flag to switch from App mode to Storybook mode in `App.tsx`. The other approach is to have an Admin Menu somewhere in the app that takes you to a "developer only" screen, which displays the Storybook. 
- I've collected all stories in one directory under `src/storybook/stories`. It might be better to have each component in `src/components` in its own directory and co-locate the tests, snapshots and stories for that component in a single directory. 
- I've included basic decorators as an example. These a good ways to write functionality that can be injected across all stories (e.g. CenteredView) or add at the …

Add Storybook

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/core/assessment/dto/AssessmentInfosRequest.ts
src/features/assessment/LevelOfIsolationScreen.tsx
src/features/assessment/fields/FaceMaskQuestion.tsx

Adds face mask question. Develops further on @MikeD-ZOE 's vitamin question (nicely done to encapsulate the creation of the dto in the object) by using an enum to clean up the typing. 
Needs translations and a full test, but is basically there.

Add face mask question

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/assessment/LevelOfIsolationScreen.tsx
src/features/assessment/YourCovidTestsScreen.tsx
src/features/assessment/fields/FaceMaskQuestion.tsx

Changes copy of questions +  moves justification text higher in the screen.

Level of Isolation Minor Copy Adjustments

---

src/features/ViralThankYouScreen.tsx

Drops the Survey Module onto the US Thank you page with new link created by Kirstin
- This Screen needs a serious cleanup.....

Adds US Survey onto thank you page

---

src/features/assessment/fields/FaceMaskQuestion.tsx

The issue is on the dropdown field. By not using an explicit android label is a temporary fix.

Fix android multiple labels

---

assets/lang/en.json

Update validation study info text. en only.

Update validation study info text

---

src/components/CalloutBox.tsx
src/core/content/ContentApiClient.ts
src/core/content/ContentService.ts
src/core/user/UserService.ts

Add parameters to the content call to get back the correct localised strings.

Add country params to fetch text content

---

src/features/patient/fields/HeightQuestion.tsx
src/features/patient/fields/WeightQuestion.tsx

[3] Fixes alignment of Height & Weight boxes
[3]
---

Fixes height and weight alignment

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/assessment/ProfileBackDateScreen.tsx
src/features/patient/YourHealthScreen.tsx
src/features/patient/fields/DiabetesOralMedsQuestion.tsx
src/features/patient/fields/DiabetesQuestions.tsx
src/features/patient/fields/DiabetesTreatmentsQuestion.tsx
src/storybook/stories/DiabetesQuestions.stories.tsx

[1] Move checkbox options inside component for i18n initialisation
[2] Add translatable error message to required diabetes type question
[3] Fix i18n initialisation issues with nested components
[4] Adds optional placeholder to questions

Diabetes question - bug fixes

---

src/components/USStudyInvite.tsx

adjust image styling

---

appConfig.ts
src/CovidApp.tsx
src/components/USStudyInvite.tsx
src/core/assessment/AssessmentCoordinator.ts
src/core/assessment/__tests__/coordinator.test.node.ts
src/features/Navigation.ts
src/features/ScreenParamList.tsx
src/features/assessment/CovidTestDetailScreen.tsx
src/features/assessment/CovidTestListScreen.tsx
src/features/assessment/CovidTestsScreen.tsx
src/features/assessment/DescribeSymptomsScreen.tsx
src/features/assessment/HealthWorkerExposureScreen.tsx
src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/LevelOfIsolationScreen.tsx
src/features/assessment/LifestyleScreen.tsx
src/features/assessment/ProfileBackDateScreen.tsx
src/features/assessment/TreatmentOtherScreen.tsx
src/features/assessment/TreatmentSelectionScreen.tsx
src/features/assessment/WhereAreYouScreen.tsx
src/features/multi-profile/ConsentForOtherScreen.tsx
src/features/multi-profile/ReportForOtherScreen.tsx
src/features/register/gb/ValidationStudyConsentScreen.tsx

- Fixes spelling of `version` in AppConfig.ts
- Moves AssessmentCoordinator to ./src/core/assesment
- Renames YourCovidTests -> CovidTests

Refactor & organise features/assessment folder

---

src/components/USStudyInvite.tsx

Quick fix for bug when using large accessibility font text.

Add scroll view to us study invite

---

src/components/SelectableButton.tsx
src/components/YesNoField.tsx
src/features/assessment/DescribeSymptomsScreen.tsx
src/features/assessment/HealthWorkerExposureScreen.tsx
src/features/patient/AboutYouScreen.tsx
src/features/patient/PreviousExposure.tsx
src/features/patient/YourHealthScreen.tsx
src/features/patient/YourWorkScreen.tsx
src/features/patient/fields/AtopyQuestions.tsx
src/features/patient/fields/BloodPressureMedicationQuestion.tsx
src/features/patient/fields/DiabetesQuestions.tsx
src/features/patient/fields/HeightQuestion.tsx
src/storybook/index.ts
src/storybook/stories/YesNoField.stories.tsx

Add new component to create better ui for yes no questions.

Yes no field

---

src/features/ThankYouUKScreen.tsx

Inject UserService rather than import / initialise a new one.

Inject user service

---

mock-server/config.ts
mock-server/mockDb.ts
mock-server/mockServer.ts
mock-server/types.ts
src/appConfig.ts
src/core/diet-study/DietStudyApiClient.ts
src/core/diet-study/dto/DietStudyRequest.ts
src/core/diet-study/dto/DietStudyResponse.ts
src/core/diet-study/dto/DietStudyTypes.ts

Add's Diet Study DTOs and Types 

[SHARED BRANCH] Add Diet Study DTO 

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/DrawerToggle.tsx
src/components/Stats/NumberIndicator.tsx
src/features/DrawerMenu.tsx
src/storybook/index.ts
src/storybook/stories/NumberIndicator.stories.tsx

Added number indicator

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/appConfig.ts
src/core/user/UserService.ts
src/features/assessment/gb/VaccineRegistryInfoScreen.tsx
src/features/assessment/gb/VaccineRegistrySignUpScreen.tsx
src/storybook/stories/ShareApp.stories.tsx

Visual styling tweaks to Vaccine Register screens.

Minor visual tweaks to both Vaccine screens

---

src/features/AppCoordinator.ts
src/features/register/ConsentScreen/ConsentScreen.tsx

Clean up missed navigation call.

Move consent navigation

---

src/core/user/UserService.ts
src/features/AppCoordinator.ts
src/features/SplashScreen.tsx
src/features/multi-profile/SelectProfileScreen.tsx

Cleans up the error handling and other functions.

Clean up app init and error handling

---

src/CovidApp.tsx
src/NavigatorService.ts
src/core/assessment/AssessmentCoordinator.ts
src/core/patient/PatientCoordinator.ts
src/features/AppCoordinator.ts
src/features/SplashScreen.tsx
src/features/register/WelcomeRepeatScreen.tsx

Refactor navigation to use navigation container reference

Refactor navigation to use navigation container reference

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/Cards/AlcoholUnitInfo.tsx
src/components/Cards/__test__/__snapshots__/AlcoholUnitInfo.test.tsx.snap
src/components/Text.tsx
src/features/DrawerMenu.tsx
src/features/diet-study/DietStudyAboutYouScreen.tsx
src/features/diet-study/DietStudyYourLifestyleScreen.tsx
src/features/diet-study/fields/AlcoholQuestons.tsx
src/features/diet-study/fields/DietDescriptionQuestion.tsx
src/features/diet-study/fields/EatingHabitQuestions.tsx
src/features/diet-study/fields/EatingWindowQuestions.tsx
src/features/diet-study/fields/ExtraWeightQuestions.tsx
src/features/diet-study/fields/FoodSecurityQuestion.tsx
src/features/diet-study/fields/HoursSleepQuestion.tsx
src/features/diet-study/fields/PhysicalActivity.tsx
src/features/diet-study/fields/ShiftWorkQuestion.tsx
src/features/diet-study/fields/SupplementQuestions.tsx
src/features/patient/fields/WeightQuestion.tsx

- Adds Questions for Screens 1 & 2 in the flow. 
- Console Logs the output for now. 
- Needs wiring up to the Server API and getting the PatientID

Diet Study Screens 1 & 2

---

src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/LifestyleScreen.tsx
src/features/assessment/TreatmentOtherScreen.tsx
src/features/assessment/TreatmentSelectionScreen.tsx
src/features/assessment/WhereAreYouScreen.tsx

Fixes broken develop branch by cleaning up remaining resetNavigation calls

Remove resetNavigation calls

---

assets/lang/en.json
src/CovidApp.tsx
src/components/Cards/BaseShareApp.tsx
src/core/diet-study/DietStudyCoordinator.ts
src/features/diet-study/DietStudyThankYouScreen.tsx

Code to handle multiple patients included but not called.

Diet study thanks

---

src/CovidApp.tsx
src/NavigatorService.ts

Refactor to move screen analytics to navigation service and out of main app file.

Move screen analytics to navigation service

---

src/features/assessment/gb/VaccineRegistrySignUpScreen.tsx

Add scroll to vaccine sign up screen

Add scroll to vaccine sign up screen

---

src/core/user/UserService.ts
src/features/diet-study/DietStudyThankYouScreen.tsx
src/features/multi-profile/SelectProfileScreen.tsx

Fix list patients and add typing

---

src/features/diet-study/DietStudyFormSubmit.hooks.tsx

Set submitting flag

---

src/features/diet-study/fields/AlcoholQuestons.tsx

If the user doesn't drink alcohol, then don't show the next alcohol related question

Add conditional to alcohol question

---

src/NavigatorService.ts
src/core/diet-study/DietStudyCoordinator.ts

Covers the case when the thank you screen is pushed independently from the drawer menu if the user has already completed the study.

Fix nav for thank you page

---

src/features/diet-study/DietStudyAboutYouScreen.tsx
src/features/diet-study/DietStudyFormSubmit.hooks.tsx
src/features/diet-study/DietStudyTypicalDietScreen.tsx
src/features/diet-study/DietStudyYourLifestyleScreen.tsx

Fix diet study for previous time period causing loop back.

fix: nav loop

---

src/components/Cards/AlcoholUnitInfo.tsx
src/components/Cards/__test__/__snapshots__/AlcoholUnitInfo.test.tsx.snap

Updates Alcohol Units: 
- Pluralise units
- Add wrapping of lines
- Correct spelling of one of the style attributes

Alcohol Units

---

assets/lang/en.json
src/features/diet-study/DietStudyThankYouScreen.tsx

- Update Copy
- Add Scroll View to Thank You page
Thank you screen need a scroll view:

Update Diet Study Copy & Scroll View on Thank You Page

---

src/NavigatorService.ts
src/core/diet-study/DietStudyApiClient.ts
src/core/diet-study/DietStudyCoordinator.ts
src/features/AppCoordinator.ts
src/features/diet-study/DietStudyThankYouScreen.tsx

Refactor nav

---

src/features/diet-study/DietStudyAboutYouScreen.tsx
src/features/diet-study/fields/ExtraWeightQuestions.tsx

Made some changes to simplify and not have to use separate state as well.

Conditionally show weight field + simplification

---

src/core/diet-study/DietStudyCoordinator.ts

Update recent diet study display name to `Recent 4 weeks`

fix: update recent diet study time period display name

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/core/diet-study/DietStudyCoordinator.ts
src/core/diet-study/dto/DietStudyRequest.ts
src/features/diet-study/fields/EatingHabitQuestions.tsx
src/features/diet-study/fields/HoursSleepQuestion.tsx

Split the sleep question into 2 (weekday and weekend), added new eating habit question and made copy changes.

New questions + copy changes

---

src/features/multi-profile/ProfileList.hooks.ts
src/features/multi-profile/SelectProfileScreen.tsx

Fix to make profiles load correctly. Removed some unnecessary code in profile hook.

Fix select profile screen

---

src/features/AppCoordinator.ts
src/features/diet-study/DietStudyThankYouScreen.tsx

Fix import errors on `Profile` type after the refactor. 

Fix types imports

---

src/components/Collections/ProfileList.tsx
src/components/ProfileCard.tsx

Edit profile was unable to be clicked, changing the TouchableOpacity being imported fixed this. Also fix some other type issues.

Fix to make edit profile button work

---

src/features/DrawerMenu.tsx

- Removes unused async function that's causes issues on startup
- Clean up unused imports and unsued variables
- Correct typo in `openPushNoticationSettings` -> `openPushNotificationSettings`

Drawer menu fixes

---

src/appConfig.ts

Missed checking in this line to PR https://github.com/zoe/covid-tracker-react-native/pull/604

Add missing line from checkin

---

assets/lang/en.json
src/components/Donate.tsx
src/features/thank-you/ThankYouUKScreen.tsx

Add UK Donation Module back into the app. 

Add Donation Module to UK page.

---

src/features/thank-you/ThankYouUKScreen.tsx

Move donate module to the top.

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/AppCoordinator.ts
src/features/diet-study/DietStudyAboutYouScreen.tsx
src/features/diet-study/DietStudyThankYouBreakScreen.tsx
src/features/diet-study/DietStudyThankYouScreen.tsx
src/features/diet-study/DietStudyYourLifestyleScreen.tsx

Minor copy and layout feedback from Sarah B.
1.     On the 2nd screen can we 'bold' the '4weeks' so it is very clear that we are asking for the past 4 weeks.
2.     After Weight, i think we should add in the Lifetsyle sub-header rather than where it currently is (so that sleep and shoftwork is included within lifestyle)
3.     The Question after 'shift work': 'which of the following statements best describes the food eaten in your househols in the past week?' should move to a Dietary Habits section. An in the drop down for this, please change the last option from text of 'didn't' to 'did not'.
4.     The 'Dietary Habits questions should start from the alcohol questions and also include the question listed above in my point '3'.
5.     Your typical Diet can stay as a subheading where it …

Diet Study Feedback

---

src/core/diet-study/dto/DietStudyTypes.ts

fix: field value typo

---

assets/lang/en.json
src/components/Text.tsx
src/features/diet-study/DietStudyAboutYouScreen.tsx
src/features/diet-study/DietStudyConsentScreen.tsx
src/features/diet-study/DietStudyThankYouScreen.tsx
src/features/diet-study/DietStudyTypicalDietScreen.tsx
src/features/diet-study/DietStudyYourLifestyleScreen.tsx

- Copy changes 
- Remove the progress bars as they are a bit inconsistent and confusing, given we have section headings
- Refresh the CTA and layout of the consent page

Update copy and progress bars.

---

src/features/multi-profile/SelectProfileScreen.tsx

Prevent excessive profile api calls, will now only call once when component is mounted.. 

fix: excessive profile api requests

---

src/features/diet-study/DietStudyThankYouScreen.tsx
src/features/thank-you/ThankYouUKScreen.tsx

Remove stray divider and donate module on thank you page

Remove stray divider and donate module on thank you page

---

src/features/patient/YourStudyScreen.tsx

Add new Mary Washington Cohort

Add new Mary Washington Cohort

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json

- Added "Currently we only support reporting for the primary registered profile." to intro text
- Updated common validation error to "Please scroll up fill in the missing details or correct the above information" 

feat: updated diet study text

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/DropdownField.tsx
src/features/diet-study/fields/EatingWindowQuestions.tsx
src/features/diet-study/fields/OtherInfoQuestion.tsx

Fixes bug with scrolling dropdown.
Adds clearer error message copy.
Adds text to intro screen to explain primary profile only.
Caps comments box at 1000 characters (in line with BE).

Hot Fix OTA for Diet Study Bugs

---

src/core/patient/PatientCoordinator.ts

Save directly the info response received from server

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/core/diet-study/DietStudyCoordinator.ts
src/core/diet-study/dto/DietStudyRequest.ts
src/core/diet-study/dto/DietStudyResponse.ts
src/features/diet-study/DietStudyThankYouBreakScreen.tsx
src/features/diet-study/DietStudyTypicalDietScreen.tsx
src/features/diet-study/fields/DietChangedQuestion.tsx

Added has diet changed question to Typical diet study screen

feat: added has diet changed question

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/diet-study/DietStudyThankYouBreakScreen.tsx

Adds explanatory text to interstitial page

Add line to interstitial page

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/core/diet-study/DietStudyCoordinator.ts
src/core/diet-study/dto/DietStudyRequest.ts
src/core/diet-study/dto/DietStudyResponse.ts
src/core/patient/PatientCoordinator.ts
src/features/diet-study/DietStudyThankYouBreakScreen.tsx
src/features/diet-study/DietStudyTypicalDietScreen.tsx
src/features/diet-study/fields/DietChangedQuestion.tsx
src/features/multi-profile/edit-profile/EditProfileScreen.tsx

OTA Release

---

mock-server/helpers.ts

JSON.Stringify() parameters were changed so that mock server would be able to run
- [✔ ] Android - Emulator
- [ ✔] Android - Physical device

Changed parameters passed in line 29

---

src/CovidApp.tsx

Replaces the component directly with the dashboard screen.

Disable bottom tab nav

---

src/features/dashboard/DashboardScreen.tsx

open link to point user to https://covid.joinzoe.com/data

feat: open link to point user to covid.joinzoe.com/data

---

src/features/dashboard/Header.tsx

fix: format-contributors-count

---

src/features/dashboard/CollapsibleHeaderScrollView.tsx
src/features/multi-profile/SelectProfileScreen.tsx

Add back button to nav bar of select profile screen

feat: add back button

---

src/features/dashboard/CollapsibleHeaderScrollView.tsx

Makes button easier to click on

feat: improved drawer toggle touch area

---

src/features/AppCoordinator.ts

Wrong service name due to code merge and refactor

fix: wrong service name due to refactoring and merge

---

.circleci/config.yml

Update memory for CircleCI

---

src/core/user/UserService.ts
src/features/AppCoordinator.ts

Fix logged user not loading next app startup 

fix: load user in AppCoordinator init

---

src/core/patient/PatientService.ts
src/features/dashboard/CollapsibleHeaderScrollView.tsx

Minor: Changes
- Removes console logs
- Correct spelling mistakes in variable names.
- User centralised colours

Correct spelling and remove console log

---

src/features/register/WelcomeRepeatScreen.tsx

HOTFIX:
Remove donate for UK screen

Remove donate for UK screen

---

src/features/thank-you/ThankYouUKScreen.tsx

feat: remove incidence module from thank you screen

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/Cards/EstimatedCasesMapCard.tsx

- Show 'Not enough contributors in this area' if active cases is null

fix: show 'not enough contributors'

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/Cards/EstimatedCasesMapCard.tsx

- Flips the logic on the null values returned. 
- Correct spelling mistake.

Fixes to Estimated Card

---

src/features/dashboard/CollapsibleHeaderScrollView.tsx

Fix padding on new Dashboard

---

src/components/Cards/EstimatedCase/EstimatedCaseCard.tsx

Use Branded Button 

---

src/features/dashboard/CollapsibleHeaderScrollView.tsx

Remove blue line in the subcontainer

---

package-lock.json
package.json

fix: add missing dependency

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/dashboard/Header.tsx

Update main cta from `Report now` to `Report today`

fix: update cta

---

src/features/patient/YourStudyScreen.tsx

Adds logic to correctly handle de-selection when a user clicks NOTA and clicks any other checkbox.

add logic to handle selecting NOTA

---

src/features/patient/NHSDetailsScreen.tsx
src/features/patient/YourStudyScreen.tsx

Fixes copy on "About Your Study" page + adds type ignore due to refactor of YourStudy screen to allow editing.

Fix/NHS copy + typing

---

src/components/Cards/EstimatedCasesMapCard.tsx

- Enable edit of property `postcode` for the main Patient

feat: enable postcode edit from map

---

src/features/AppCoordinator.ts

Fix code base not using the right variable

fix: use the right variable

---

src/core/user/dto/UserAPIContracts.ts
src/features/multi-profile/edit-profile/EditLocationScreen.tsx

Bug that caused the postcode change not to be sent to the server correctly

Use null instead of undefined as undefined doesn't attach to payload

---

assets/lang/en-US.json
assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/assessment/HowYouFeelScreen.tsx
src/features/multi-profile/edit-profile/EditLocationScreen.tsx
src/features/multi-profile/edit-profile/EditProfileScreen.tsx

Adds Swedish + Spanish translations  + removes country flag to launch in those countrys.

Enable Edit location in the US + Sweden

---

assets/lang/en-US.json
assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/assessment/HowYouFeelScreen.tsx
src/features/multi-profile/edit-profile/EditLocationScreen.tsx
src/features/multi-profile/edit-profile/EditProfileScreen.tsx

* add SE translations
* remove country filtering
* padding on disclaimer
* add spanish translation and title

Enable Edit location in the US + Sweden (#743)

---

src/features/multi-profile/edit-profile/EditProfileCoordinator.ts

I reintroduced this bug when the older Patient data PR was merged.

Fix reintroduced bug

---

src/appConfig.ts
src/features/register/sv/PrivacyPolicySVScreen.tsx

Updates privacy policy to reflect change in export behaviour.

Update privacy policy for sweden

---

.circleci/config.yml
README.md
package-lock.json
package.json

This PR adds coverall.io as a 3rd party product that integrates jest's coverage reports with CircleCI.

Add Coverall Code Coverage

---

src/features/register/Welcome1Screen.tsx

Update landing page to improve login usability

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/Cards/SchoolNetworks.tsx
src/core/schools/Schools.dto.ts

- Fixes type errors with new size property in the DTOs
- Adds keys to prevent warnings in repeated groups
- Fix mismatched i18n string
- Add plural / singular text for children in a group
- Change new line character from \r -> \n which doesn't seem to render on Android devices.

Fixes School Group List Module

---

src/features/register/RegisterScreen.tsx

Bug fix to make sure new GB users are shown the dashboard screen on first register

Fetch startup info and set screen on register 

---

src/components/Cards/SchoolNetworks.tsx
src/utils/array.ts

If the account has multiple profiles in one group then don't show duplicate groups.

Deduplicate school groups in SchoolNetworks component

---

assets/lang/sv-SE.json
src/features/dashboard/CollapsibleHeaderScrollView.tsx

- Reverse dashboard header changes to fix Android display
- Remove duplicate keys in Swedish json file

Revert Dashboard Header changes

---

src/features/dashboard/DashboardScreen.tsx

Add featured blog post on Dashboard. 
(This was hotfixed last night).

Add featured blog post on Dashboard

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/school-network/JoinSchoolScreen.tsx

Add copy to School Join Page to discourage mis-use.

Add copy disclaimer

---

src/features/multi-profile/ReportForOtherScreen.tsx
src/features/multi-profile/edit-profile/EditProfileCoordinator.ts
src/features/school-network/JoinSchoolScreen.tsx
src/features/thank-you/ThankYouUKScreen.tsx

Fix report for others button not using the right nav params in `ThankYouUKScreen.tsx`
Will be adding detox to @petermason expo eject branch and add screen level tests there instead

fix: report for others route params

---

src/utils/array.ts

fix: missing sort fn export

---

src/core/assessment/AssessmentCoordinator.ts

Disables the route to LevelOfIsolation screen, removal of code can be done in the future if we are 100% sure we don't need it.

Disable LevelOfIsolation route

---

.circleci/config.yml

Use slack context to post in a channel, one merged can remove webhook in project settings level

chores: using slack context in circle-ci

---

src/features/multi-profile/edit-profile/EditProfileCoordinator.ts

Show school network to uk users only

fix: only show school network to uk users

---

assets/carto/estimated-cases.html

Update map legends on mobile to sync up with web.

feature: update carto map legends

---

src/core/diet-study/dto/DietStudyTypes.ts

Incorrect keys were used on the front end.

Fix food availability keys

---

src/features/AppCoordinator.ts

Uses variable in class rather than scoped function 

fix: use class var not scoped var in a fn

---

assets/lang/en-US.json
src/features/diet-study/fields/FoodSecurityQuestion.tsx

- Fixes the DietStudy Food Availability DTO 
- Updates the copy on the Consent Page

Fix Diet Study DTO & Update Copy

---

assets/lang/en-US.json
assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/Cards/AlcoholUnitInfo.tsx
src/components/Cards/__test__/__snapshots__/AlcoholUnitInfo.test.tsx.snap

Using translation strings to properly format. Hopefully should be small enough for smaller screens

Fix alcohol sizing info

---

src/core/assessment/AssessmentCoordinator.ts
src/core/patient/PatientService.ts
src/core/patient/PatientState.ts
src/core/user/dto/UserAPIContracts.ts

Remove lifestyle questions!

---

src/features/diet-study/fields/FoodSecurityQuestion.tsx

Remove validation on this question as a quick fix. It's trying to validate the checkbox options, but they are only displayed when Food Security is not the top option.

Remove validation on new question

---

src/features/school-network/SchoolDashboardScreen.tsx

PR into feature branch as a suggestion.
- Use momentJS (used elsewhere in our code base) for pretty date time formatting.

Use momentJS for date time format

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/CovidApp.tsx
src/components/Cards/SchoolNetworks.tsx
src/core/assessment/AssessmentCoordinator.ts
src/core/patient/PatientService.ts
src/core/patient/PatientState.ts
src/core/user/dto/UserAPIContracts.ts
src/features/ScreenParamList.tsx
src/features/covid-tests/CovidTestConfirmScreen.tsx
src/features/covid-tests/CovidTestDetailScreen.tsx

Add confirmation screen if the user logs a positive test and has a school network.

Notify school

---

src/features/dashboard/DashboardScreen.tsx

Call refresh token from the new Dashboard (UK)

Call refresh token from the new Dashboard (UK)

---

src/components/Cards/SchoolNetworks.tsx

Temporarily disable this until product give the green light,.

Disable School Group Dashboard

---

src/features/thank-you/ThankYouUKScreen.tsx

Blog post is not ready for publication yet.

Hide blog article

---

assets/charts/trendline-explore.html
src/components/Stats/TrendLineChart.tsx
src/features/dashboard/TrendlineScreen.tsx

fix(trendline): fixed scale for covid cases

---

src/core/assessment/AssessmentCoordinator.ts
src/features/multi-profile/ReportForOtherScreen.tsx

Tidy some nav code and stop users going back to completed assessments from the thank you screens

Minor fixes

---

src/components/Cards/EstimatedCase/TrendlineCard.tsx
src/components/Stats/TrendLineChart.tsx
src/features/dashboard/TrendlineScreen.tsx

Add share trendline feature to dashboard and provide android fix

---

src/components/DropdownField.tsx
src/features/patient/fields/BloodGroupQuestion.tsx

Puts 'I dont know' to the top and then adds 20px to the minimum drop down height in order to partially expose any additional items.

Fix blood group order and minimum dropdown height

---

assets/charts/trendline-overview.html

fix(trendline-overview): disable smooth chart

---

src/features/covid-tests/CovidTestListScreen.tsx

Phones with very small screens/extra large text couldn't see their covid test list.

Make whole covid test screen scrollable

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/Cards/FacebookSE.tsx
src/features/register/ConsentScreen/ConsentScreenSE.tsx
src/features/thank-you/ThankYouScreen.tsx

Simple copy changes requested by Swedish team.
## Test List
## Adding Tests

Swedish copy changes

---

src/components/Cards/EstimatedCase/DeltaTag.tsx

display negative number as positive

Display negative trend delta a positive int

---

src/components/Cards/EstimatedCase/DeltaTag.tsx
src/core/content/state/contentSlice.ts
src/features/AppCoordinator.ts
src/features/dashboard/DashboardScreen.tsx

- Fix bug introduced by Cohort assignment
- Fix race condition on feature flag / trendline data 
- Fix delta tag showing negative values

OTA - Fixes (Analytics / Feature Flag / Trendline)

---

assets/carto/estimated-cases.html

Request from data science team

feat(map): carto url updated

---

assets/lang/en.json

- [x ] I have run `npm run test:i18n`

Add copy to school code page

---

assets/lang/en.json

Simple copy update: 'Your child's Unique School Network Code should have been shared with you by a school representative. Please contact the school if you cannot find this code.'

update school code copy

---

src/features/school-network/partials/SelectedSchool.tsx

remove ref to package via shared index and make path relative. removes require cycle

resolve require cycle

---

src/components/Text.tsx
src/features/diet-study/DietStudyAboutYouScreen.tsx
src/features/diet-study/DietStudyTypicalDietScreen.tsx
src/features/diet-study/DietStudyYourLifestyleScreen.tsx
src/features/diet-study/fields/AlcoholQuestons.tsx
src/features/diet-study/fields/DietDescriptionQuestion.tsx
src/features/diet-study/fields/EatingHabitQuestions.tsx
src/features/diet-study/fields/EatingWindowQuestions.tsx
src/features/diet-study/fields/FruitNVegConsumptionQuestions.tsx
src/features/diet-study/fields/HoursSleepQuestion.tsx
src/features/diet-study/fields/MilkTypeQuestion.tsx
src/features/diet-study/fields/OtherInfoQuestion.tsx
src/features/diet-study/fields/SupplementQuestions.tsx
src/features/menu/DrawerMenu.tsx

Due to previous margin rework for the assessments, the margins for these screens were not checked and needed fixing.

Fix margins on fields for diet study

---

src/features/register/WelcomeRepeatScreen.tsx

This PR guards against the /startup_info/ endpoin returning a 4xx error and AsyncStorage being black / no fallback for the user count. This might not affect many users - but could be a problem for new people installing the app or re-installing the app. 

Add null check

---

src/core/patient/PatientCoordinator.ts
src/core/patient/PatientService.ts
src/core/patient/PatientState.ts
src/features/multi-profile/edit-profile/EditProfileCoordinator.ts
src/features/patient/AboutYouScreen.tsx

The YourWork screen has been disabled for minors and the last 4 questions of AboutYou also get hidden if the entered age is a minor.

Disable features for minors

---

src/features/patient/fields/DiabetesOralMedsQuestion.tsx
src/features/patient/fields/DiabetesQuestions.tsx
src/features/patient/fields/DiabetesTreatmentsQuestion.tsx

- Remove justification text which is outdated on the Profile Screen 
- Fixes margins

Diabetes cleanup

---

src/core/assessment/AssessmentCoordinator.ts
src/features/multi-profile/edit-profile/EditProfileCoordinator.ts

This was introduced in https://github.com/zoe/covid-tracker-react-native/pull/878
A few minor flows are "broken" / display the wrong rendering of the SelectProfile screen
- Goto Edit Profile -> Study Membership -> Join NHS Study and then complete. 
- From ThankYouScreen -> Report for Others

(bug) Fix navigation issues

---

src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/fields/OtherSymptomsQuestions.tsx
src/features/covid-tests/CovidTestDetailScreen.tsx
src/features/covid-tests/CovidTestListScreen.tsx
src/features/covid-tests/NHSTestDetailScreen.tsx
src/features/covid-tests/fields/CovidTestDateQuestion.tsx
src/features/covid-tests/fields/CovidTestTimeQuestion.tsx
src/features/covid-tests/fields/NHSTestDateQuestion.tsx
src/features/multi-profile/ConsentForOtherScreen.tsx
src/features/multi-profile/CreateProfileScreen.tsx
src/features/multi-profile/edit-profile/EditLocationScreen.tsx
src/features/school-network/forms/school.tsx
src/features/school-network/forms/university.tsx

Fixes alignment issues:
- Dividers on CovidTestListScreen And HowYouFeelScreen
- Join school
- Join university
- COVID Test Details for NHS and Regular
- Add border radius to the "Other Symptoms" TextArea

Fix alignment issues

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/appConfig.ts
src/components/Checkbox.tsx
src/core/assessment/dto/AssessmentInfosRequest.ts
src/features/assessment/GeneralSymptomsScreen.tsx
src/features/assessment/fields/GeneralSymptomsQuestions.tsx
src/features/assessment/fields/SymptomsTypes.tsx
src/features/register/Welcome1Screen.tsx

Testing the OTA mechanism on stage. Adds two commits:
- Removes env text from welcome screen (#908)
- Changes to Fever Questions (#904)

(chore) Deploy develop -> stage

---

.circleci/config.yml

Switch branch naming convention

---

src/components/Cards/school-networks/SchoolStats.tsx

Updates the activation threshold to 10% for School Groups

Update threshold to 10%

---

src/components/Cards/school-networks/Card.tsx

add key to mapped element and remove useless container

---

app.json
package.json

Bump client app version to `2.1.0`. 
Bump OTA channel version to `2.1.0`.

chore(app): version bump

---

src/components/Cards/school-networks/SchoolStats.tsx

remove duplicate text

---

assets/lang/en.json
src/components/BigGreenTick.tsx
src/components/ExternalCallout.tsx
src/features/thank-you/ThankYouUKScreen.tsx

Tidying up margins, a few text colours/fonts and add icon at the top.

Tidy up thank you uk screen

---

src/components/Cards/EstimatedCase/EstimatedCaseCard.tsx
src/components/Cards/EstimatedCase/TrendlineCard.tsx
src/components/Cards/EstimatedCasesMapCard.tsx
src/components/Cards/school-networks/styles.ts
src/components/ExternalCallout.tsx
src/features/dashboard/DashboardScreen.tsx

Pushes all horizontal margins up to the parent (dashboard screen in this case). All vertical margins normalised.

Fixes dashboard margins

---

src/components/NewProfileCard.tsx
src/components/ProfileCard.tsx

The cards need a general clean up but for now this fixes the bug.

Normalise profile card heights

---

assets/lang/sv-SE.json

Copy changes requested by Camilla

Copy changes

---

src/components/Cards/EstimatedCasesMapCard.tsx

cancel async action when using useEffect

fix memory leak on useEffect

---

assets/lang/sv-SE.json

Update Swedish copy to fix capitalisation, a typo and some changes in wording.

Update Swedish copy

---

assets/lang/en.json
src/components/Cards/EstimatedCasesMapCard.tsx

restyle map card

---

src/core/user/UserService.ts
src/features/AppCoordinator.ts

FIXES:
from homescreen, log out
land on the 3 flags page
PRESS THE BACK BUTTON
Relaunch the app, either directly to the homescreen (on a Samsung A50) or back to 3 flags on my OnePlus 6T.
if relaunched to 3 flags, press the back button.
if app exits, relaunch it
=> HOME SCREEN!

test for user

---

.circleci/config.yml

- Remove unused CircleCI commands for legacy-ota
- Remove build phase on feature branch to speed up tests.

Clean up CircleCI on feature branches 

---

src/components/Cards/EstimatedCasesMapCard.tsx

Match Figma Design
IOS
ANDROID

Match figma design

---

src/CovidApp.tsx
src/core/assessment/AssessmentCoordinator.ts
src/features/ScreenParamList.tsx
src/features/thank-you/ThankYouSEScreen.tsx
src/features/thank-you/ThankYouUSScreen.tsx
src/features/thank-you/index.ts
src/routes/main-navigator.tsx

Main fix is in file assessmentCoordinator line 202 and 208.
The rest is a rename of the thank you screens to reflect their usage.

Fix incorrect home screen when US users goes back from thank you screen

---

src/core/assessment/AssessmentCoordinator.ts

Stops users going back to report dose symptoms.

Resets stack after finishing daily dose symptoms report

---

assets/lang/en.json

fix: update copy for trendline title

---

app.json
package.json

Bump version for new build

---

App.tsx
ios/Podfile.lock
react-native.config.js
src/CovidApp.tsx
yarn.lock

Remove unnecessary font load. If this fails during boot, the app fails.

remove unwated font load

---

assets/lang/en.json

Update share copy

---

src/features/login/LoginScreen.tsx
src/features/register/RegisterScreen.tsx

Prevent the multi or unnecessary tap of the submit button on forms

prevent multi tap: login, register

---

src/components/Screen.tsx
src/features/covid-tests/CovidTestListScreen.tsx
src/features/vaccines/VaccineListScreen.tsx

Align margins and background colour of vaccine and test screens

Align margins and background colour

---

.circleci/config.yml

chore(ci): disable rollback

---

assets/charts/trendline-explore.html

Test postcode `SL23GX`, and need to test against production backend 

fix(white-trendline): issue setting min / max range

---

src/features/thank-you/ThankYouUKScreen.tsx

Fix content not showing inside thankyou screen

fix(app-content): remove extra styling

---

src/features/assessment/gb/VaccineRegistrySignUpScreen.tsx

remove unnecessary styling that causes layout error

remove unnecessary styling

---

src/features/login/LoginScreen.tsx

Refactor class component to be a function

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
ios/Podfile.lock
package.json
src/core/vaccine/dto/VaccineRequest.ts
src/features/vaccines/fields/DoseSymptomsQuestions.tsx
yarn.lock

[1] Add bruising to Dose Symptoms
## HTTP Requests
- [2] Update the yarn reset command to something useful
- [3] Sync lock files

Add bruising to Dose Symptoms

---

assets/lang/sv-SE.json
src/components/ExternalCallout.tsx

Fixes this mismatched i18n strings:

Fix mis-matched translation string

---

ios/Covid.xcodeproj/project.pbxproj
ios/Podfile

- Remove sentry command cause by a merge conflict.

Fix iOS build

---

src/features/vaccines/AboutYourVaccineScreen.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx

Currently the formik validation is incorrectly blocking me from editing a vaccine (e.g. to set the type) and leaving the Batch Number / Lot Number blank. 
Quick fix for this!

Make lot number optional

---

assets/lang/en-US.json
assets/lang/en.json
assets/lang/es.json
src/components/PatientHeader.tsx
src/components/Screen.tsx
src/features/vaccines/VaccineFindInfoScreen.tsx
src/features/vaccines/VaccineLogSymptomsInfoScreen.tsx
src/features/vaccines/components/VaccineCard.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx

Bug fixes on vaccine form date and button

---

src/components/Cards/EstimatedCase/TrendlineCard.tsx

white screen fix

---

ios/Covid.xcodeproj/project.pbxproj
ios/Podfile
ios/Podfile.lock

Merge iOS 11 fixes to release to `master`
* chore(ios-11): update
* chore(ios-11): run ci on this branch
* chore(ci): remove tmp branch
Co-authored-by: snack-0verflow <36766508+cm-hvg@users.noreply.github.com>

Chores/ios 11 (#1097)

---

android/app/build.gradle
fastlane/Fastfile
ios/Podfile.lock
src/core/Analytics.ts

- Fixes versionCode for play store upgrade
- Fixes native dependencies.

Version 2.3.0 

---

android/gradle.properties

Trying to fix multiple kotlin sessions issue on CI

chores(android): increase jvm args size

---

assets/lang/en.json
assets/lang/es.json

Typo on received

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/core/assessment/dto/AssessmentInfosRequest.ts
src/features/assessment/fields/HeadSymptomsQuestions.tsx

Add two fields to assessment

---

src/core/assessment/AssessmentCoordinator.ts
src/features/AppCoordinator.ts
src/features/ScreenParamList.tsx
src/features/vaccines/AboutYourVaccineScreen.tsx

- Removes the userService from the AssessmentCoordinator. (Not used)
- Adds missing screen to ScreenParamList (VaccineFindInfo)
- Fix mismatched arg color -> colorIcon

Clean Up: Type errors & remove userService

---

src/features/dashboard/DashboardScreen.tsx

hot fix remove temp button from dashboard

hot fix remove temp button from dashboard

---

src/features/vaccines/AboutYourVaccineScreen.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx

Various fixes and check on validation, mostly around the Formik validation for dose 2 items.

Vaccine form validation fixes

---

src/features/dashboard/DashboardScreen.tsx

remove temp button from dashboard

remove temp button from dashboard

---

src/core/state/store.ts

provides an array of state properties that can be ignored by asyncStorage
will be populated by future pr's

add whitelist to redux persist

---

android/app/build.gradle

Fastlane incrementing isn't working. Will fix this in a future PR.

Manually bump android versionCode

---

android/app/build.gradle

Manually bump android versionCode (#1125)

---

src/features/vaccines/AboutYourVaccineScreen.tsx

Tweaks the "has date changed" logic for when saving vaccine data.
Previously the addition of a new dose would run a comparison on existing date two (undefined) to new value, and determine it had changed.
Also stored this logic in new consts for easier reading.

V3 Vaccine Date change logic

---

src/features/vaccines/VaccineListScreen.tsx
src/features/vaccines/components/VaccineCard.tsx

Disables the vaccine list CTA when there is missing required data on dose 1 or 2 - date, brand and description.

V3Vaccine force user to update missing data

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/Cards/ShareVaccineCard.tsx
src/components/Screens/share/container.tsx
src/components/Screens/share/index.tsx
src/features/dashboard/DashboardScreen.tsx
src/features/dashboard/DashboardUSScreen.tsx
src/features/vaccines/AboutYourVaccineScreen.tsx
src/features/vaccines/VaccineFindInfoScreen.tsx
src/features/vaccines/fields/VaccineHesitancyQuestions.tsx
src/features/vaccines/fields/VaccineNameQuestion.tsx

OTA release, develop -> master, for Swedish vaccine changes

---

src/features/vaccines/fields/VaccineDoseQuestion.tsx

Min date is none, unless GB/US - in which case it is overwritten by first date for vaccine.

Min date for vaccine

---

src/features/vaccines/fields/VaccineDoseQuestion.tsx

Hotfix for min date for sweden

Min date for vaccine (#1139)

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/mental-health/screens/MentalHealthChanges.tsx
src/features/mental-health/screens/MentalHealthFrequency.tsx
src/features/mental-health/screens/MentalHealthHistory.tsx
src/features/mental-health/screens/MentalHealthLearning.tsx
src/features/mental-health/screens/MentalHealthStart.tsx
src/features/mental-health/screens/MentalHealthSupport.tsx

add 'Next' and 'Start' translations for navigation

add translations for navigation

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json

Updates share message text. EN only.

Share mesage for mental health flow

---

src/core/state/mental-health/state/slice/index.ts
src/core/state/mental-health/state/types/index.ts
src/features/dashboard/DashboardScreen.tsx
src/features/mental-health/screens/MentalHealthEnd.tsx
src/features/mental-health/screens/MentalHealthHistory.tsx
src/features/mental-health/screens/MentalHealthLearning.tsx
src/features/mental-health/screens/MentalHealthModal.tsx

add completed to mental health flow

---

assets/lang/en-US.json
src/features/mental-health/screens/MentalHealthModal.tsx

- For the video, I created some fake padding in order to simulate a model that goes off the screen. 
- All this PR does is wrap the modal in scroll view. 
- Also fixes Karestan's name

Wrap Mental Health Modal in scroll view

---

assets/lang/en-US.json
src/features/mental-health/screens/MentalHealthHistory.tsx
src/features/mental-health/screens/MentalHealthModal.tsx

- Fix to mental health routing (#1165)

OTA Release 2.4.0 

---

src/features/diet-study-playback/v2/DietStudyEmailModal.tsx

hot fix add close icon to modal

---

src/NavigatorService.ts
src/features/diet-study-playback/v2/DietStudy.tsx
src/features/diet-study-playback/v2/DietStudyGlobal.tsx
src/features/diet-study-playback/v2/DietStudyGut.tsx
src/features/diet-study-playback/v2/DietStudyTraditional.tsx
src/features/mental-health/screens/MentalHealthChanges.tsx
src/features/mental-health/screens/MentalHealthEnd.tsx
src/features/mental-health/screens/MentalHealthFrequency.tsx
src/features/mental-health/screens/MentalHealthHistory.tsx
src/features/mental-health/screens/MentalHealthLearning.tsx
src/features/mental-health/screens/MentalHealthSupport.tsx

remove duplicate page tracking events

---

src/features/diet-study-playback/v2/DietStudy.tsx
src/features/diet-study-playback/v2/DietStudyGlobal.tsx
src/features/diet-study-playback/v2/DietStudyGut.tsx
src/features/diet-study-playback/v2/DietStudyTraditional.tsx

add subscribe to main diet study page and remove from child pages

---

src/features/dashboard/DashboardUSScreen.tsx

hot fix to add logic to us dashboard

add logic for us dashboard to display mental health study

---

src/features/dashboard/DashboardUSScreen.tsx

add logic for us dashboard to display mental health study (#1176)

OTA Release Channel 2.4.0

---

src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/TreatmentSelectionScreen.tsx
src/features/assessment/WhereAreYouScreen.tsx

Prevent multiple clicks during transion between screens

add is submitting logic to pages without any

---

src/components/USStudyInvite.tsx

adjust us study invite layout size

---

src/core/Experiments.ts
src/features/diet-study-playback/v2/DietStudyCard.tsx
src/features/diet-study-playback/v2/DietStudyModal.tsx

Removes the A/B test for the DietScore playback. 
V2 is the winner!

Remove A/B test

---

package.json
src/components/BrandedButton/__tests__/BrandedButton.test.tsx
src/components/USStudyInvite.tsx
src/core/Experiments.ts
src/features/AppCoordinator.ts
src/features/assessment/HowYouFeelScreen.tsx
src/features/assessment/TreatmentSelectionScreen.tsx
src/features/assessment/WhereAreYouScreen.tsx
src/features/diet-study-playback/components/action-card/index.tsx
src/features/diet-study-playback/v2/DietStudyCard.tsx
src/features/diet-study-playback/v2/DietStudyModal.tsx
src/features/mental-health/partials/questions/frequency-question.tsx

Features
- Removes A/B Test for Diet Study flow
Fixes 
- Frequency question disabled logic
- Double submits on Assessment Flows
- Wrong Analytics events on the Diet Study Feedback
- US Study Invite Modal

OTA Release 2.4.0

---

src/features/diet-study-playback/v2/DietStudyGut.tsx

The Gut Screen is incorrectly using the diet_scores instead of the gut_friendly_score

Fix wrong scores

---

src/features/vaccines/AboutYourVaccineScreen.tsx
src/features/vaccines/VaccineDoseSymptomsScreen.tsx
src/features/vaccines/VaccineHesitancyScreen.tsx
src/features/vaccines/VaccineListMissingModal.tsx
src/features/vaccines/VaccineLogSymptomsInfoScreen.tsx
src/features/vaccines/components/VaccineCard.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx
src/features/vaccines/fields/VaccineHesitancyQuestions.tsx
src/features/vaccines/fields/VaccineNameQuestion.tsx

- Remove unused & optimise imports
- Cleaner declaration of object
- Ensure all code paths return a value
- Fix lint warnings for equality 
- Rename function with correct camel case
- Remove unused functions and variables

Vaccines Refactor

---

src/features/dashboard/TrendlineScreen.tsx
src/features/dashboard/index.ts

The builds are failing, because in PR #1192 I forgot to remove the following lines in this PR.

Fix missed check in

---

src/features/vaccines/VaccineListScreen.tsx

Use shared util function openWebLink on the Swedish vaccine banner.

Use openWebLink

---

assets/lang/en.json
src/features/validation-study/ValidationStudyInfoScreen.tsx
src/features/validation-study/ValidationStudyIntroScreen.tsx

Fixes branded button on the Validation Study into + info screen:

Fix branded buttons

---

src/components/layouts/pages/basic-page/index.tsx
src/features/AppCoordinator.ts
src/features/ScreenParamList.tsx
src/features/anniversary/data/index.ts
src/features/anniversary/index.ts
src/features/anniversary/partials/highlight.tsx
src/features/anniversary/partials/index.ts
src/features/anniversary/partials/progress-bar.tsx
src/features/anniversary/partials/progress-bars.tsx
src/features/anniversary/partials/report-card.tsx
src/features/anniversary/partials/reported-event.tsx
src/features/anniversary/partials/study-card.tsx
src/features/anniversary/partials/timeline-card.tsx
src/features/anniversary/partials/timeline-node.tsx
src/features/anniversary/partials/timeline.tsx
src/features/anniversary/screens/anniversary.tsx
src/features/anniversary/screens/index.ts
src/features/dashboard/DashboardScreen.tsx
src/features/index.ts
src/routes/anniversary/index.tsx
src/routes/index.ts
src/routes/main-navigator/index.tsx
src/themes/theme/typography.ts
src/themes/types/typography.ts

The templates for all the timeline UI components

wip: initial set up

---

.circleci/config.yml

We only use it in the build process.

Pin expo-cli to 4.3.0.

---

src/features/anniversary/partials/report-card.tsx
src/features/anniversary/partials/timeline-introduction.tsx

Minor tweaks for timeline

---

src/features/anniversary/partials/finding-card.tsx
src/features/anniversary/partials/report-card.tsx
src/features/anniversary/partials/study-card.tsx
src/features/anniversary/partials/timeline-header.tsx
src/features/anniversary/partials/timeline-introduction.tsx
src/features/anniversary/partials/timeline-node.tsx
src/features/anniversary/partials/timeline.tsx
src/features/anniversary/screens/anniversary.tsx

- Fixes to copy and spacing
- Change moment date formatting
- Fixes to typography to better match designs

Timeline QA - Copy and visual deviations from Figma

---

src/features/anniversary/partials/impact-timeline-card.tsx
src/features/anniversary/partials/timeline-node.tsx
src/features/dashboard/DashboardScreen.tsx

- Check for null strings to prevent TextRenderered error
- Aligns card padding with the figma

Check for null strings on Node in the event timeline

---

src/features/anniversary/partials/finding-card.tsx
src/features/dashboard/DashboardScreen.tsx
src/features/diet-study-playback/v2/DietStudyCard.tsx

- Change DietStudy card so the whole thing is tappable f496d29
- Add DietScore card to UK Homepage 44ac494
- Fix navigation to DietScore from TimelineCard with a hack b334e52
https://user-images.githubusercontent.com/7824212/112848542-1798f780-90a0-11eb-9d47-6f68fba64ada.mov

Fixed to DietScores

---

src/core/state/settings/slice/index.ts
src/core/state/settings/types/index.ts
src/core/user/dto/UserAPIContracts.ts
src/features/dashboard/DashboardScreen.tsx
src/features/thank-you/ThankYouUKScreen.tsx

The Timeline feature should only be displayed if instructed to by the backend.

Wire Timeline to feature flag

---

src/features/anniversary/partials/timeline-node.tsx
src/features/anniversary/partials/timeline.tsx
src/features/anniversary/types/index.ts

Simple approach for the timeline summary nodes.
EG screenshot with existing data for mock :

timeline SUMMARY_NODE

---

src/features/anniversary/partials/timeline-node.tsx

Change font weight for readability

---

src/features/dashboard/DashboardScreen.tsx

override feature event to prioritise timeline

---

src/core/user/UserService.ts
src/features/register/RegisterScreen.tsx

This will remove many utterly redundant 500 errors from our server logs.
Co-authored-by: Ben Fox <deathbycornishpastie@hotmail.com>

OTA:  Switch to version 2 of the register endpoint (#1239)

---

src/features/vaccines/fields/VaccineDoseQuestion.tsx

function was missing call so throwing a silent render error

call uncalled function

---

src/features/dashboard/DashboardScreen.tsx
src/features/dashboard/DashboardUSScreen.tsx

https://www.notion.so/joinzoe/powered-by-ZOE-CTA-bc3ce66fcb6b4628a97c64ae4f62bc1a

make powered by zoe a cta to zoe website

---

src/features/covid-tests/components/CovidTestRow.tsx

https://www.notion.so/joinzoe/Add-years-to-the-COVID-Test-List-screen-c26351e81f944dbf877d4eaae767e7fd

add year to test date

---

package.json
src/core/state/app/slice/__tests__/index.ts
src/core/state/app/slice/index.ts

Redux test

---

src/features/vaccines/VaccineListScreen.tsx
src/features/vaccines/components/VaccineWarning.tsx
src/features/vaccines/components/index.ts

Add's a vaccine banner as a stop gap until we understand the build issues with the useMessage() components. 
https://user-images.githubusercontent.com/7824212/114582586-a13bee00-9c78-11eb-9fbb-cd083232cf68.mov
https://user-images.githubusercontent.com/7824212/114582625-a9942900-9c78-11eb-9f90-b4ed29a95339.mov

Add a vaccine banner

---

.circleci/config.yml

Add npx to CircleCI

---

src/features/dashboard/DashboardScreen.tsx
src/features/dashboard/DashboardUSScreen.tsx

Reverting this as legal haven't signed off.

Revert "make powered by zoe a cta to zoe website

---

catalog-info.yaml

Metadata yaml file describing the service. 
This will be auto discovered by backstage.

Add product catlalog description for backstage

---

src/components/ExternalCallout.tsx

Removed the object destructuring in the ExternalCallout component.

---

README.md

CircleCI failed to build the previous PR into master saying that the job won't run because the PR is closed?! Seeing if this will fix it / it was a transient error.

Retrigger Release Build on Master

---

src/features/patient/YourHealthScreen.tsx
src/features/patient/fields/BloodPressureMedicationQuestion.tsx
src/themes/theme/grid.ts
src/themes/theme/typography.ts

Undo a few changes made by ESLint fix.

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/covid-tests/CovidTestListScreen.tsx
src/features/long-covid/screens/LongCovidQuestionPageOne.tsx
src/features/long-covid/screens/consts.questions.tsx

Initial minor QA items for long covid

Initial QA

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/components/EmptyState.tsx
src/core/state/mental-health-playback/slice.ts
src/core/state/mental-health-playback/types.ts
src/core/user/dto/UserAPIContracts.ts
src/features/AppCoordinator.ts
src/features/dashboard/DashboardScreen.tsx
src/features/mental-health-playback/MentalHealthPlaybackModal.tsx
src/features/mental-health-playback/components/BarChart.tsx
src/features/mental-health-playback/components/Insights.tsx
src/features/mental-health-playback/screens/MHPGeneralScreen.tsx
src/features/mental-health-playback/screens/MHPIntroductionScreen.tsx
src/features/mental-health/MentalHealthApiClient.ts
src/types/mental-health-playback/index.ts

Make a distinction in the mental health playback based on the users cohorts

---

assets/lang/en.json
src/components/Text.tsx
src/features/long-covid/screens/LongCovidQuestionPageOne.tsx

Adds some UI improvements included coloured highlight text to Long COVID

Long COVID QA

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml

(cherry picked from commit da89b242661ce2159bcbf7a6e52ba4f2881ac750)
Merging hotfix back in to develop.

Correct deep link and bump version code (#1309)

---

src/features/assessment/ProfileBackDateScreen.tsx
src/features/assessment/TreatmentOtherScreen.tsx
src/features/assessment/partials/USStudyInvite.tsx
src/features/covid-tests/CovidTestDetailScreen.tsx
src/features/covid-tests/NHSTestDetailScreen.tsx
src/features/multi-profile/edit-profile/EditLocationScreen.tsx
src/features/patient/AboutYouScreen.tsx
src/features/patient/YourStudyScreen.tsx
src/features/school-network/SchoolGroupListScreen.tsx
src/features/vaccines/AboutYourVaccineScreen.tsx
src/features/vaccines/VaccineDoseSymptomsScreen.tsx
src/features/vaccines/VaccineHesitancyScreen.tsx

Fix visual regression in branded buttons

---

src/components/layouts/pages/basic-page/index.tsx
src/features/long-covid/screens/LongCovidStart.tsx

- Removes some text
- Pushes button to the the bottom

Visuals Changes to Long COVID Screen

---

src/core/localisation/LocalisationService.ts
src/features/long-covid/screens/LongCovidQuestionPageOne.tsx
src/features/long-covid/screens/consts.questions.tsx
src/features/long-covid/types.ts

Fixes issue in which the "other" symptom was mapping to checkbox vs textfield

Long covid "other" symptom fix

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/Services.ts
src/components/Modal.tsx
src/core/VersionUpdateModal.tsx
src/core/api/GeneralApiClient.ts
src/features/anniversary/screens/AnniversaryModal.tsx
src/features/dashboard/DashboardScreen.tsx
src/features/diet-study-playback/v2/DietStudyModal.tsx
src/features/long-covid/LongCovidApiClient.ts
src/features/mental-health-playback/MentalHealthPlaybackModal.tsx
src/features/mental-health/MentalHealthApiClient.ts
src/features/mental-health/screens/MentalHealthModal.tsx

Register a user event on modal show.

---

src/components/layouts/pages/basic-page/index.tsx
src/components/layouts/safe-layout/index.tsx
src/features/diet-study-playback/v2/DietStudy.tsx
src/features/diet-study-playback/v2/DietStudyGlobal.tsx
src/features/diet-study-playback/v2/DietStudyGut.tsx
src/features/diet-study-playback/v2/DietStudyTraditional.tsx
src/features/login/LoginScreen.tsx
src/features/mental-health-playback/screens/MHPGeneralScreen.tsx
src/features/mental-health-playback/screens/MHPThankYouScreen.tsx
src/features/vaccines/VaccineListScreen.tsx
src/themes/theme/styling.ts

Partly rewrote the LoginScreen to support the back navigation button.

---

README.md
package.json
src/features/CountrySelectScreen.tsx
src/features/mental-health-playback/screens/MHPBlogPostScreen.tsx

Remove the children from the WebView to prevent the crash on Android.

---

src/features/mental-health-playback/screens/MHPRatingScreen.tsx

Solve the shadow ui bug on Android.

---

assets/lang/sv-SE.json
src/features/long-covid/screens/LongCovidQuestionPageOne.tsx
src/features/long-covid/screens/consts.questions.tsx

Swedish dropdowns

---

src/features/long-covid/screens/LongCovidQuestionPageOne.tsx

I made the boo boo of not fully testing PR #1351
This actually fixes it:

Fix translations for drop downs

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/long-covid/screens/LongCovidQuestionPageOne.tsx
src/features/mental-health-playback/components/Insights.tsx
src/features/mental-health-playback/screens/MHPGeneralScreen.tsx
src/features/mental-health-playback/screens/MHPThankYouScreen.tsx

Implemented all the qa feedback points.

---

.gitignore
src/features/vaccines/fields/VaccineDoseQuestion.tsx
src/features/vaccines/fields/VaccineNameQuestion.tsx

Fixed some Typescript errors that I noticed when I was looking at #1356 .
n/a
no

Fix Typescript errors for VaccineNameQuestion

---

.github/CODEOWNERS

Added a codeowners file to the repo to enable default reviewers on github

---

.github/CODEOWNERS
.gitignore
src/core/content/state/contentSlice.ts
src/features/vaccines/fields/VaccineDoseQuestion.tsx
src/features/vaccines/fields/VaccineNameQuestion.tsx

OTA Release to 2.5.0
- Add's J&J vaccine for UK users (Julia)
- Fixes postcode bug on dashboard (Ben

OTA Release 2.5.0

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json

Removed hesitancy code that was still left behind.

---

src/components/InfoCard.tsx
src/components/cards/ShareVaccineCard.tsx
src/core/assessment/AssessmentCoordinator.ts
src/core/vaccine/VaccineApiClient.ts
src/features/assessment/GeneralSymptomsScreen.tsx
src/features/assessment/GutStomachSymptomsScreen.tsx
src/features/assessment/HeadSymptomsScreen.tsx
src/features/assessment/OtherSymptomsScreen.tsx
src/features/assessment/ThroatChestSymptomsScreen.tsx
src/features/assessment/partials/USStudyInvite.tsx
src/features/dashboard/TrendlineScreen.tsx

Removed unnecessary react fragment components.

---

src/features/dashboard/DashboardScreen.tsx
src/features/thank-you/ThankYouUKScreen.tsx

Reorder Home and TY screen cards (#1375)

OTA Release to 2.5.0

---

src/core/state/store.ts

Ignore the middleware took too long warning.

---

src/components/Checkbox.tsx
src/components/DropdownField.tsx
src/components/TwoButtonModal.tsx
src/components/inputs/ButtonsGroup.tsx
src/components/stats/NumberIndicator.tsx
src/features/assessment/HowYouFeelScreen.tsx
src/features/multi-profile/ArchiveConfirmationModal.tsx
src/features/patient/NHSDetailsScreen.tsx
src/features/patient/NHSIntro.tsx
src/features/patient/YourStudyScreen.tsx
src/features/school-network/SchoolDashboardScreen.tsx
src/features/school-network/SchoolHowToScreen.tsx
src/features/school-network/SchoolIntroScreen.tsx
src/features/thank-you/components/AppRating.tsx
src/features/vaccines/components/VaccineWarning.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx
src/features/vaccines/fields/VaccineNameQuestion.tsx
src/storybook/stories/DiabetesQuestions.stories.tsx

Replace the native-base with the react-native View component.

---

src/components/cards/school-networks/index.tsx
src/features/dashboard/DashboardScreen.tsx

Prevent the school card from being empty.

---

CONTRIBUTING.md
README.md

Addition of style guide section to CONTRIBUTING.md. Added link to this section in the README file as well.
Note, though it looks like lots of changes have been made to README, it's just the link in line 137 that I added. The rest are auto-linting changes.
n/a
n/a
n/a
This needs to be fleshed out in more detail.

Added a style guide section to our contribution guide

---

src/components/Forms.tsx
src/features/multi-profile/ConsentForOtherScreen.tsx
src/features/multi-profile/CreateProfileScreen.tsx
src/features/password-reset/ResetPasswordScreen.tsx
src/features/patient/AboutYouScreen.tsx

Using `.bind(this)` is the old school way of React!

Replaced .bind(this) with anonymous functions.

---

assets/lang/en.json
src/components/YesNoField.tsx
src/components/inputs/ButtonsGroup.tsx
src/features/patient/YourWorkScreen.tsx

Add form validation to WorkScreen form.
Ticket: https://www.notion.so/joinzoe/Form-validation-About-Your-Work-18502fe8c79544278c7268179a379a49

Form validation for WorkScreen form

---

assets/lang/sv-SE.json
src/components/Forms.tsx
src/features/vaccines/AboutYourVaccineScreen.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx
src/features/vaccines/fields/VaccineNameQuestion.tsx

Add form validation to AboutYourVaccineScreen form.
No specific ticket, logging finished refactors here: https://www.notion.so/joinzoe/Fun-with-Forms-d66ad33a88694d8aaa86777fbf4a75b8#22636d7c049b4132a051c3a5eea4b8fc
Notes:
- @bionara I change the `FormWrapper` props slightly to include `style`.
- Had to amend how we were updating Formik values in the calendar picker because value was not updating immediately upon date selection.

AboutYourVaccineScreen form validation refactor

---

src/features/patient/YourHealthScreen.tsx
src/features/patient/fields/AtopyQuestions.tsx
src/features/patient/fields/BloodGroupQuestion.tsx
src/features/patient/fields/BloodPressureMedicationQuestion.tsx
src/features/patient/fields/DiabetesQuestions.tsx
src/features/patient/fields/DiabetesTreatmentsQuestion.tsx

Add form validation to AboutYourHealthScreen form.
No specific ticket, logging finished refactors here: https://www.notion.so/joinzoe/Fun-with-Forms-d66ad33a88694d8aaa86777fbf4a75b8#22636d7c049b4132a051c3a5eea4b8fc

Form validation refactor

---

src/components/inputs/RadioInput.tsx

Add accessibility props to the RadioInput component.

---

src/features/assessment/HealthWorkerExposureScreen.tsx

- Add form validation to HealthWorkerExposure form.
- No specific ticket, logging finished refactors here: https://www.notion.so/joinzoe/Fun-with-Forms-d66ad33a88694d8aaa86777fbf4a75b8#22636d7c049b4132a051c3a5eea4b8fc

HealthWorkerExposure form validation refactor

---

src/components/Checkbox.tsx
src/components/DropdownField.tsx
src/components/Forms.tsx
src/components/GenericTextField.tsx
src/components/inputs/ButtonsGroup.tsx
src/components/inputs/RadioInput.tsx
src/features/covid-tests/fields/CovidTestDateQuestion.tsx
src/features/password-reset/fields/ResetPasswordForm.tsx
src/features/patient/fields/HeightQuestion.tsx
src/features/patient/fields/WeightQuestion.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx

Use a special space to prevent the asterisk from being word-wrapped.

---

src/Services.ts
src/components/content/__test__/FeaturedContentList.test.tsx
src/core/api/GeneralApiClient.ts
src/core/assessment/AssessmentApiClient.ts
src/core/content/ContentApiClient.ts
src/core/diet-score/DietScoreApiClient.ts
src/core/push-notifications/PushNotificationApiClient.ts
src/core/schools/SchoolService.ts
src/core/vaccine/VaccineApiClient.ts
src/features/long-covid/LongCovidApiClient.ts
src/features/mental-health/MentalHealthApiClient.ts

Fixes for services / apis

---

src/features/reconsent/screens/ReconsentDiseasePreferencesScreen.tsx

https://www.notion.so/joinzoe/Re-consent-Flow-Convert-list-of-disease-cards-to-FlatList-on-Disease-Preferences-screen-dcae6e726f8a435e86e1961a6342de9c
n/a

Convert disease card list to FlatList component

---

src/NavigatorService.ts
src/components/DrawerToggle.tsx
src/components/Screen.tsx
src/features/AppCoordinator.ts
src/features/diet-study-playback/v2/DietStudy.tsx
src/features/splash/SplashScreen.tsx

Refactor ScreenName type

---

src/components/buttons/branded-button/index.tsx
src/components/inputs/CheckboxTextInputList.tsx
src/core/state/reconsent/slice/index.ts
src/core/state/reconsent/types/index.ts
src/features/AppCoordinator.ts
src/features/reconsent/components/ReconsentScreen.tsx
src/features/reconsent/screens/ReconsentFeedbackScreen.tsx
src/features/reconsent/screens/ReconsentReconsiderScreen.tsx

Integrated the feedback form into Redux.

---

src/core/content/ContentApiClient.ts
src/core/content/ContentService.ts
src/features/reconsent/screens/ReconsentNewsletterSignupScreen.tsx

https://www.notion.so/joinzoe/Re-consent-Flow-Newsletter-Signup-screen-connect-with-api-a6f501a27a184ac6a6fd651eea545894

Save disease research newsletter preference to backend

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/core/state/reconsent/types/index.ts
src/core/user/dto/UserAPIContracts.ts
src/features/reconsent/screens/ReconsentDiseasePreferencesScreen.tsx

Update disease preferences name fields to match backend

---

src/core/user/dto/UserAPIContracts.ts
src/features/reconsent/screens/ReconsentReconsiderScreen.tsx
src/features/reconsent/screens/ReconsentRequestConsentScreen.tsx

Send boolean field to confirm research consent has been asked

---

src/features/reconsent/screens/ReconsentReconsiderScreen.tsx

Fix: reconsent asked boolean should be PATCHed on patient model, not user model

---

src/core/state/reconsent/slice/index.ts
src/features/reconsent/components/ReconsentScreen.tsx
src/features/reconsent/screens/ReconsentReconsiderScreen.tsx

Embed the Vimeo video inside a WebView.

---

assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
src/features/reconsent/screens/ReconsentIntroductionScreen.tsx

- Remove mention of approval from KCL
- Amendment to "no" consent wording

Copy changes following Christina's KCL ethics call

---

src/features/dashboard/DashboardScreen.tsx
src/features/reconsent/components/DiseaseCard.tsx
src/features/reconsent/components/ShowMore.tsx
src/features/reconsent/screens/ReconsentDiseasePreferencesScreen.tsx

https://www.notion.so/joinzoe/017c3de591604a7b89d0b69e3c37b279?v=0133357df3ed42e1bd42c1e0d7afcf45&p=5e6431491fd64f1b836bbebc25901837
Before:
After:

Add shadow on Android to the disease cards.

---

src/features/reconsent/screens/ReconsentReconsiderScreen.tsx

Show a loading spinner before the video has loaded.

---

android/gradle.properties
assets/lang/en.json
assets/lang/es.json
assets/lang/sv-SE.json
metro.config.js

- Fix build configuration to ensure asset pipeline was being bundled.
- Grammar fixes for MHP.

App store release 2.6.0

---

src/features/patient/AboutYouScreen.tsx
src/features/patient/PreviousExposureScreen.tsx
src/features/patient/YourHealthScreen.tsx

- Fixed the following forms: `AboutYou`, `PreviousExposure` and `YourHealth`
[comment]: <> (Description of the feature or fix)
[comment]: <> (Include link to Figma designs, if relevant)
[comment]: <> (Include link to Notion ticket, if relevant)

2.6.0-ota-10

---

src/features/assessment/ProfileBackDateScreen.tsx
src/features/covid-tests/CovidTestTabbedListsScreen.tsx

- Bugfix that prevented vertical scrolling within a nested FlatList.
- Bugfix that caused people to be stuck on the ProfileBackDateScreen.

2.6.0-ota-13

---

src/features/register/ConsentScreen/ConsentScreen.tsx

Remove postConsent from the registration for GB people.
[comment]: <> (Description of the feature or fix)
[comment]: <> (Include link to Figma designs, if relevant)
[comment]: <> (Include link to Notion ticket, if relevant)

2.6.0-ota-16

---

assets/lang/en-US.json
assets/lang/en.json
assets/lang/sv-SE.json
src/components/inputs/RadioInput.tsx
src/core/assessment/AssessmentCoordinator.ts
src/core/patient/PatientService.ts
src/core/patient/PatientState.ts
src/core/vaccine/dto/VaccineRequest.ts
src/features/ScreenParamList.tsx
src/features/covid-tests/CovidTestTabbedListsScreen.tsx
src/features/vaccines/AboutYourVaccineScreen.tsx
src/features/vaccines/VaccineListScreen.tsx
src/features/vaccines/VaccineTabbedListsScreen.tsx
src/features/vaccines/__tests__/AboutYourVaccineScreenUpdated.test.tsx
src/features/vaccines/__tests__/VaccineListScreenUpdated.test.tsx
src/features/vaccines/components/VaccineDoseRow.tsx
src/features/vaccines/fields/VaccineDoseQuestion.tsx
src/features/vaccines/fields/VaccineFluMechanismQuestion.tsx
src/features/vaccines/fields/VaccineTypeQuestion.tsx
src/features/vaccines/index.ts

- Allows patients to log flu vaccines

2.6.0-ota-17
